// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetria.proto

package smgo.telemetria;

public final class Telemetria {
  private Telemetria() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EventoTelemetriaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smgo.telemetria.EventoTelemetria)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 identificadorEvento = 1;</code>
     * @return The identificadorEvento.
     */
    int getIdentificadorEvento();

    /**
     * <code>.smgo.posicao.Posicionamento posicao = 2;</code>
     * @return Whether the posicao field is set.
     */
    boolean hasPosicao();
    /**
     * <code>.smgo.posicao.Posicionamento posicao = 2;</code>
     * @return The posicao.
     */
    smgo.posicao.PosicionamentoOuterClass.Posicionamento getPosicao();
    /**
     * <code>.smgo.posicao.Posicionamento posicao = 2;</code>
     */
    smgo.posicao.PosicionamentoOuterClass.PosicionamentoOrBuilder getPosicaoOrBuilder();

    /**
     * <pre>
     * aceleracao em m/s^2
     * </pre>
     *
     * <code>double aceleracao = 3;</code>
     * @return The aceleracao.
     */
    double getAceleracao();

    /**
     * <pre>
     * rotacao do motor, em rpm
     * </pre>
     *
     * <code>uint32 rpm = 4;</code>
     * @return The rpm.
     */
    int getRpm();

    /**
     * <pre>
     * tempo que o veiculo permaneceu em violacao dos parametros, em segundos
     * </pre>
     *
     * <code>uint32 tempoViolacao = 5;</code>
     * @return The tempoViolacao.
     */
    int getTempoViolacao();

    /**
     * <code>double porcentagemCombustivel = 6;</code>
     * @return Whether the porcentagemCombustivel field is set.
     */
    boolean hasPorcentagemCombustivel();
    /**
     * <code>double porcentagemCombustivel = 6;</code>
     * @return The porcentagemCombustivel.
     */
    double getPorcentagemCombustivel();

    /**
     * <code>uint32 combustivelRestanteLitros = 7;</code>
     * @return Whether the combustivelRestanteLitros field is set.
     */
    boolean hasCombustivelRestanteLitros();
    /**
     * <code>uint32 combustivelRestanteLitros = 7;</code>
     * @return The combustivelRestanteLitros.
     */
    int getCombustivelRestanteLitros();

    public smgo.telemetria.Telemetria.EventoTelemetria.CombustivelCase getCombustivelCase();
  }
  /**
   * <pre>
   * mensagens de evento de telemetria
   * </pre>
   *
   * Protobuf type {@code smgo.telemetria.EventoTelemetria}
   */
  public static final class EventoTelemetria extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smgo.telemetria.EventoTelemetria)
      EventoTelemetriaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EventoTelemetria.newBuilder() to construct.
    private EventoTelemetria(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventoTelemetria() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EventoTelemetria();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EventoTelemetria(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              identificadorEvento_ = input.readUInt32();
              break;
            }
            case 18: {
              smgo.posicao.PosicionamentoOuterClass.Posicionamento.Builder subBuilder = null;
              if (posicao_ != null) {
                subBuilder = posicao_.toBuilder();
              }
              posicao_ = input.readMessage(smgo.posicao.PosicionamentoOuterClass.Posicionamento.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(posicao_);
                posicao_ = subBuilder.buildPartial();
              }

              break;
            }
            case 25: {

              aceleracao_ = input.readDouble();
              break;
            }
            case 32: {

              rpm_ = input.readUInt32();
              break;
            }
            case 40: {

              tempoViolacao_ = input.readUInt32();
              break;
            }
            case 49: {
              combustivel_ = input.readDouble();
              combustivelCase_ = 6;
              break;
            }
            case 56: {
              combustivel_ = input.readUInt32();
              combustivelCase_ = 7;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smgo.telemetria.Telemetria.internal_static_smgo_telemetria_EventoTelemetria_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smgo.telemetria.Telemetria.internal_static_smgo_telemetria_EventoTelemetria_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smgo.telemetria.Telemetria.EventoTelemetria.class, smgo.telemetria.Telemetria.EventoTelemetria.Builder.class);
    }

    /**
     * Protobuf enum {@code smgo.telemetria.EventoTelemetria.TipoEventoTelemetria}
     */
    public enum TipoEventoTelemetria
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ACELERACAO_BRUSCA = 0;</code>
       */
      ACELERACAO_BRUSCA(0),
      /**
       * <code>FREADA_BRUSCA = 1;</code>
       */
      FREADA_BRUSCA(1),
      /**
       * <code>CURVA_BRUSCA = 2;</code>
       */
      CURVA_BRUSCA(2),
      /**
       * <code>ROTACAO_FORA_FAIXA_IDEAL = 3;</code>
       */
      ROTACAO_FORA_FAIXA_IDEAL(3),
      /**
       * <code>DADOS_COMBUSTIVEL = 4;</code>
       */
      DADOS_COMBUSTIVEL(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ACELERACAO_BRUSCA = 0;</code>
       */
      public static final int ACELERACAO_BRUSCA_VALUE = 0;
      /**
       * <code>FREADA_BRUSCA = 1;</code>
       */
      public static final int FREADA_BRUSCA_VALUE = 1;
      /**
       * <code>CURVA_BRUSCA = 2;</code>
       */
      public static final int CURVA_BRUSCA_VALUE = 2;
      /**
       * <code>ROTACAO_FORA_FAIXA_IDEAL = 3;</code>
       */
      public static final int ROTACAO_FORA_FAIXA_IDEAL_VALUE = 3;
      /**
       * <code>DADOS_COMBUSTIVEL = 4;</code>
       */
      public static final int DADOS_COMBUSTIVEL_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TipoEventoTelemetria valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static TipoEventoTelemetria forNumber(int value) {
        switch (value) {
          case 0: return ACELERACAO_BRUSCA;
          case 1: return FREADA_BRUSCA;
          case 2: return CURVA_BRUSCA;
          case 3: return ROTACAO_FORA_FAIXA_IDEAL;
          case 4: return DADOS_COMBUSTIVEL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<TipoEventoTelemetria>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          TipoEventoTelemetria> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<TipoEventoTelemetria>() {
              public TipoEventoTelemetria findValueByNumber(int number) {
                return TipoEventoTelemetria.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return smgo.telemetria.Telemetria.EventoTelemetria.getDescriptor().getEnumTypes().get(0);
      }

      private static final TipoEventoTelemetria[] VALUES = values();

      public static TipoEventoTelemetria valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private TipoEventoTelemetria(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:smgo.telemetria.EventoTelemetria.TipoEventoTelemetria)
    }

    private int combustivelCase_ = 0;
    private java.lang.Object combustivel_;
    public enum CombustivelCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      PORCENTAGEMCOMBUSTIVEL(6),
      COMBUSTIVELRESTANTELITROS(7),
      COMBUSTIVEL_NOT_SET(0);
      private final int value;
      private CombustivelCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static CombustivelCase valueOf(int value) {
        return forNumber(value);
      }

      public static CombustivelCase forNumber(int value) {
        switch (value) {
          case 6: return PORCENTAGEMCOMBUSTIVEL;
          case 7: return COMBUSTIVELRESTANTELITROS;
          case 0: return COMBUSTIVEL_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public CombustivelCase
    getCombustivelCase() {
      return CombustivelCase.forNumber(
          combustivelCase_);
    }

    public static final int IDENTIFICADOREVENTO_FIELD_NUMBER = 1;
    private int identificadorEvento_;
    /**
     * <code>uint32 identificadorEvento = 1;</code>
     * @return The identificadorEvento.
     */
    @java.lang.Override
    public int getIdentificadorEvento() {
      return identificadorEvento_;
    }

    public static final int POSICAO_FIELD_NUMBER = 2;
    private smgo.posicao.PosicionamentoOuterClass.Posicionamento posicao_;
    /**
     * <code>.smgo.posicao.Posicionamento posicao = 2;</code>
     * @return Whether the posicao field is set.
     */
    @java.lang.Override
    public boolean hasPosicao() {
      return posicao_ != null;
    }
    /**
     * <code>.smgo.posicao.Posicionamento posicao = 2;</code>
     * @return The posicao.
     */
    @java.lang.Override
    public smgo.posicao.PosicionamentoOuterClass.Posicionamento getPosicao() {
      return posicao_ == null ? smgo.posicao.PosicionamentoOuterClass.Posicionamento.getDefaultInstance() : posicao_;
    }
    /**
     * <code>.smgo.posicao.Posicionamento posicao = 2;</code>
     */
    @java.lang.Override
    public smgo.posicao.PosicionamentoOuterClass.PosicionamentoOrBuilder getPosicaoOrBuilder() {
      return getPosicao();
    }

    public static final int ACELERACAO_FIELD_NUMBER = 3;
    private double aceleracao_;
    /**
     * <pre>
     * aceleracao em m/s^2
     * </pre>
     *
     * <code>double aceleracao = 3;</code>
     * @return The aceleracao.
     */
    @java.lang.Override
    public double getAceleracao() {
      return aceleracao_;
    }

    public static final int RPM_FIELD_NUMBER = 4;
    private int rpm_;
    /**
     * <pre>
     * rotacao do motor, em rpm
     * </pre>
     *
     * <code>uint32 rpm = 4;</code>
     * @return The rpm.
     */
    @java.lang.Override
    public int getRpm() {
      return rpm_;
    }

    public static final int TEMPOVIOLACAO_FIELD_NUMBER = 5;
    private int tempoViolacao_;
    /**
     * <pre>
     * tempo que o veiculo permaneceu em violacao dos parametros, em segundos
     * </pre>
     *
     * <code>uint32 tempoViolacao = 5;</code>
     * @return The tempoViolacao.
     */
    @java.lang.Override
    public int getTempoViolacao() {
      return tempoViolacao_;
    }

    public static final int PORCENTAGEMCOMBUSTIVEL_FIELD_NUMBER = 6;
    /**
     * <code>double porcentagemCombustivel = 6;</code>
     * @return Whether the porcentagemCombustivel field is set.
     */
    @java.lang.Override
    public boolean hasPorcentagemCombustivel() {
      return combustivelCase_ == 6;
    }
    /**
     * <code>double porcentagemCombustivel = 6;</code>
     * @return The porcentagemCombustivel.
     */
    @java.lang.Override
    public double getPorcentagemCombustivel() {
      if (combustivelCase_ == 6) {
        return (java.lang.Double) combustivel_;
      }
      return 0D;
    }

    public static final int COMBUSTIVELRESTANTELITROS_FIELD_NUMBER = 7;
    /**
     * <code>uint32 combustivelRestanteLitros = 7;</code>
     * @return Whether the combustivelRestanteLitros field is set.
     */
    @java.lang.Override
    public boolean hasCombustivelRestanteLitros() {
      return combustivelCase_ == 7;
    }
    /**
     * <code>uint32 combustivelRestanteLitros = 7;</code>
     * @return The combustivelRestanteLitros.
     */
    @java.lang.Override
    public int getCombustivelRestanteLitros() {
      if (combustivelCase_ == 7) {
        return (java.lang.Integer) combustivel_;
      }
      return 0;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (identificadorEvento_ != 0) {
        output.writeUInt32(1, identificadorEvento_);
      }
      if (posicao_ != null) {
        output.writeMessage(2, getPosicao());
      }
      if (java.lang.Double.doubleToRawLongBits(aceleracao_) != 0) {
        output.writeDouble(3, aceleracao_);
      }
      if (rpm_ != 0) {
        output.writeUInt32(4, rpm_);
      }
      if (tempoViolacao_ != 0) {
        output.writeUInt32(5, tempoViolacao_);
      }
      if (combustivelCase_ == 6) {
        output.writeDouble(
            6, (double)((java.lang.Double) combustivel_));
      }
      if (combustivelCase_ == 7) {
        output.writeUInt32(
            7, (int)((java.lang.Integer) combustivel_));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (identificadorEvento_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, identificadorEvento_);
      }
      if (posicao_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPosicao());
      }
      if (java.lang.Double.doubleToRawLongBits(aceleracao_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, aceleracao_);
      }
      if (rpm_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, rpm_);
      }
      if (tempoViolacao_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, tempoViolacao_);
      }
      if (combustivelCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(
              6, (double)((java.lang.Double) combustivel_));
      }
      if (combustivelCase_ == 7) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(
              7, (int)((java.lang.Integer) combustivel_));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smgo.telemetria.Telemetria.EventoTelemetria)) {
        return super.equals(obj);
      }
      smgo.telemetria.Telemetria.EventoTelemetria other = (smgo.telemetria.Telemetria.EventoTelemetria) obj;

      if (getIdentificadorEvento()
          != other.getIdentificadorEvento()) return false;
      if (hasPosicao() != other.hasPosicao()) return false;
      if (hasPosicao()) {
        if (!getPosicao()
            .equals(other.getPosicao())) return false;
      }
      if (java.lang.Double.doubleToLongBits(getAceleracao())
          != java.lang.Double.doubleToLongBits(
              other.getAceleracao())) return false;
      if (getRpm()
          != other.getRpm()) return false;
      if (getTempoViolacao()
          != other.getTempoViolacao()) return false;
      if (!getCombustivelCase().equals(other.getCombustivelCase())) return false;
      switch (combustivelCase_) {
        case 6:
          if (java.lang.Double.doubleToLongBits(getPorcentagemCombustivel())
              != java.lang.Double.doubleToLongBits(
                  other.getPorcentagemCombustivel())) return false;
          break;
        case 7:
          if (getCombustivelRestanteLitros()
              != other.getCombustivelRestanteLitros()) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDENTIFICADOREVENTO_FIELD_NUMBER;
      hash = (53 * hash) + getIdentificadorEvento();
      if (hasPosicao()) {
        hash = (37 * hash) + POSICAO_FIELD_NUMBER;
        hash = (53 * hash) + getPosicao().hashCode();
      }
      hash = (37 * hash) + ACELERACAO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAceleracao()));
      hash = (37 * hash) + RPM_FIELD_NUMBER;
      hash = (53 * hash) + getRpm();
      hash = (37 * hash) + TEMPOVIOLACAO_FIELD_NUMBER;
      hash = (53 * hash) + getTempoViolacao();
      switch (combustivelCase_) {
        case 6:
          hash = (37 * hash) + PORCENTAGEMCOMBUSTIVEL_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              java.lang.Double.doubleToLongBits(getPorcentagemCombustivel()));
          break;
        case 7:
          hash = (37 * hash) + COMBUSTIVELRESTANTELITROS_FIELD_NUMBER;
          hash = (53 * hash) + getCombustivelRestanteLitros();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smgo.telemetria.Telemetria.EventoTelemetria parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.telemetria.Telemetria.EventoTelemetria parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.telemetria.Telemetria.EventoTelemetria parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.telemetria.Telemetria.EventoTelemetria parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.telemetria.Telemetria.EventoTelemetria parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.telemetria.Telemetria.EventoTelemetria parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.telemetria.Telemetria.EventoTelemetria parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.telemetria.Telemetria.EventoTelemetria parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.telemetria.Telemetria.EventoTelemetria parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smgo.telemetria.Telemetria.EventoTelemetria parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.telemetria.Telemetria.EventoTelemetria parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.telemetria.Telemetria.EventoTelemetria parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smgo.telemetria.Telemetria.EventoTelemetria prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * mensagens de evento de telemetria
     * </pre>
     *
     * Protobuf type {@code smgo.telemetria.EventoTelemetria}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smgo.telemetria.EventoTelemetria)
        smgo.telemetria.Telemetria.EventoTelemetriaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smgo.telemetria.Telemetria.internal_static_smgo_telemetria_EventoTelemetria_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smgo.telemetria.Telemetria.internal_static_smgo_telemetria_EventoTelemetria_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smgo.telemetria.Telemetria.EventoTelemetria.class, smgo.telemetria.Telemetria.EventoTelemetria.Builder.class);
      }

      // Construct using smgo.telemetria.Telemetria.EventoTelemetria.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        identificadorEvento_ = 0;

        if (posicaoBuilder_ == null) {
          posicao_ = null;
        } else {
          posicao_ = null;
          posicaoBuilder_ = null;
        }
        aceleracao_ = 0D;

        rpm_ = 0;

        tempoViolacao_ = 0;

        combustivelCase_ = 0;
        combustivel_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smgo.telemetria.Telemetria.internal_static_smgo_telemetria_EventoTelemetria_descriptor;
      }

      @java.lang.Override
      public smgo.telemetria.Telemetria.EventoTelemetria getDefaultInstanceForType() {
        return smgo.telemetria.Telemetria.EventoTelemetria.getDefaultInstance();
      }

      @java.lang.Override
      public smgo.telemetria.Telemetria.EventoTelemetria build() {
        smgo.telemetria.Telemetria.EventoTelemetria result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smgo.telemetria.Telemetria.EventoTelemetria buildPartial() {
        smgo.telemetria.Telemetria.EventoTelemetria result = new smgo.telemetria.Telemetria.EventoTelemetria(this);
        result.identificadorEvento_ = identificadorEvento_;
        if (posicaoBuilder_ == null) {
          result.posicao_ = posicao_;
        } else {
          result.posicao_ = posicaoBuilder_.build();
        }
        result.aceleracao_ = aceleracao_;
        result.rpm_ = rpm_;
        result.tempoViolacao_ = tempoViolacao_;
        if (combustivelCase_ == 6) {
          result.combustivel_ = combustivel_;
        }
        if (combustivelCase_ == 7) {
          result.combustivel_ = combustivel_;
        }
        result.combustivelCase_ = combustivelCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smgo.telemetria.Telemetria.EventoTelemetria) {
          return mergeFrom((smgo.telemetria.Telemetria.EventoTelemetria)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smgo.telemetria.Telemetria.EventoTelemetria other) {
        if (other == smgo.telemetria.Telemetria.EventoTelemetria.getDefaultInstance()) return this;
        if (other.getIdentificadorEvento() != 0) {
          setIdentificadorEvento(other.getIdentificadorEvento());
        }
        if (other.hasPosicao()) {
          mergePosicao(other.getPosicao());
        }
        if (other.getAceleracao() != 0D) {
          setAceleracao(other.getAceleracao());
        }
        if (other.getRpm() != 0) {
          setRpm(other.getRpm());
        }
        if (other.getTempoViolacao() != 0) {
          setTempoViolacao(other.getTempoViolacao());
        }
        switch (other.getCombustivelCase()) {
          case PORCENTAGEMCOMBUSTIVEL: {
            setPorcentagemCombustivel(other.getPorcentagemCombustivel());
            break;
          }
          case COMBUSTIVELRESTANTELITROS: {
            setCombustivelRestanteLitros(other.getCombustivelRestanteLitros());
            break;
          }
          case COMBUSTIVEL_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smgo.telemetria.Telemetria.EventoTelemetria parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smgo.telemetria.Telemetria.EventoTelemetria) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int combustivelCase_ = 0;
      private java.lang.Object combustivel_;
      public CombustivelCase
          getCombustivelCase() {
        return CombustivelCase.forNumber(
            combustivelCase_);
      }

      public Builder clearCombustivel() {
        combustivelCase_ = 0;
        combustivel_ = null;
        onChanged();
        return this;
      }


      private int identificadorEvento_ ;
      /**
       * <code>uint32 identificadorEvento = 1;</code>
       * @return The identificadorEvento.
       */
      @java.lang.Override
      public int getIdentificadorEvento() {
        return identificadorEvento_;
      }
      /**
       * <code>uint32 identificadorEvento = 1;</code>
       * @param value The identificadorEvento to set.
       * @return This builder for chaining.
       */
      public Builder setIdentificadorEvento(int value) {
        
        identificadorEvento_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 identificadorEvento = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentificadorEvento() {
        
        identificadorEvento_ = 0;
        onChanged();
        return this;
      }

      private smgo.posicao.PosicionamentoOuterClass.Posicionamento posicao_;
      private com.google.protobuf.SingleFieldBuilderV3<
          smgo.posicao.PosicionamentoOuterClass.Posicionamento, smgo.posicao.PosicionamentoOuterClass.Posicionamento.Builder, smgo.posicao.PosicionamentoOuterClass.PosicionamentoOrBuilder> posicaoBuilder_;
      /**
       * <code>.smgo.posicao.Posicionamento posicao = 2;</code>
       * @return Whether the posicao field is set.
       */
      public boolean hasPosicao() {
        return posicaoBuilder_ != null || posicao_ != null;
      }
      /**
       * <code>.smgo.posicao.Posicionamento posicao = 2;</code>
       * @return The posicao.
       */
      public smgo.posicao.PosicionamentoOuterClass.Posicionamento getPosicao() {
        if (posicaoBuilder_ == null) {
          return posicao_ == null ? smgo.posicao.PosicionamentoOuterClass.Posicionamento.getDefaultInstance() : posicao_;
        } else {
          return posicaoBuilder_.getMessage();
        }
      }
      /**
       * <code>.smgo.posicao.Posicionamento posicao = 2;</code>
       */
      public Builder setPosicao(smgo.posicao.PosicionamentoOuterClass.Posicionamento value) {
        if (posicaoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          posicao_ = value;
          onChanged();
        } else {
          posicaoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.smgo.posicao.Posicionamento posicao = 2;</code>
       */
      public Builder setPosicao(
          smgo.posicao.PosicionamentoOuterClass.Posicionamento.Builder builderForValue) {
        if (posicaoBuilder_ == null) {
          posicao_ = builderForValue.build();
          onChanged();
        } else {
          posicaoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.smgo.posicao.Posicionamento posicao = 2;</code>
       */
      public Builder mergePosicao(smgo.posicao.PosicionamentoOuterClass.Posicionamento value) {
        if (posicaoBuilder_ == null) {
          if (posicao_ != null) {
            posicao_ =
              smgo.posicao.PosicionamentoOuterClass.Posicionamento.newBuilder(posicao_).mergeFrom(value).buildPartial();
          } else {
            posicao_ = value;
          }
          onChanged();
        } else {
          posicaoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.smgo.posicao.Posicionamento posicao = 2;</code>
       */
      public Builder clearPosicao() {
        if (posicaoBuilder_ == null) {
          posicao_ = null;
          onChanged();
        } else {
          posicao_ = null;
          posicaoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.smgo.posicao.Posicionamento posicao = 2;</code>
       */
      public smgo.posicao.PosicionamentoOuterClass.Posicionamento.Builder getPosicaoBuilder() {
        
        onChanged();
        return getPosicaoFieldBuilder().getBuilder();
      }
      /**
       * <code>.smgo.posicao.Posicionamento posicao = 2;</code>
       */
      public smgo.posicao.PosicionamentoOuterClass.PosicionamentoOrBuilder getPosicaoOrBuilder() {
        if (posicaoBuilder_ != null) {
          return posicaoBuilder_.getMessageOrBuilder();
        } else {
          return posicao_ == null ?
              smgo.posicao.PosicionamentoOuterClass.Posicionamento.getDefaultInstance() : posicao_;
        }
      }
      /**
       * <code>.smgo.posicao.Posicionamento posicao = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          smgo.posicao.PosicionamentoOuterClass.Posicionamento, smgo.posicao.PosicionamentoOuterClass.Posicionamento.Builder, smgo.posicao.PosicionamentoOuterClass.PosicionamentoOrBuilder> 
          getPosicaoFieldBuilder() {
        if (posicaoBuilder_ == null) {
          posicaoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              smgo.posicao.PosicionamentoOuterClass.Posicionamento, smgo.posicao.PosicionamentoOuterClass.Posicionamento.Builder, smgo.posicao.PosicionamentoOuterClass.PosicionamentoOrBuilder>(
                  getPosicao(),
                  getParentForChildren(),
                  isClean());
          posicao_ = null;
        }
        return posicaoBuilder_;
      }

      private double aceleracao_ ;
      /**
       * <pre>
       * aceleracao em m/s^2
       * </pre>
       *
       * <code>double aceleracao = 3;</code>
       * @return The aceleracao.
       */
      @java.lang.Override
      public double getAceleracao() {
        return aceleracao_;
      }
      /**
       * <pre>
       * aceleracao em m/s^2
       * </pre>
       *
       * <code>double aceleracao = 3;</code>
       * @param value The aceleracao to set.
       * @return This builder for chaining.
       */
      public Builder setAceleracao(double value) {
        
        aceleracao_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * aceleracao em m/s^2
       * </pre>
       *
       * <code>double aceleracao = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAceleracao() {
        
        aceleracao_ = 0D;
        onChanged();
        return this;
      }

      private int rpm_ ;
      /**
       * <pre>
       * rotacao do motor, em rpm
       * </pre>
       *
       * <code>uint32 rpm = 4;</code>
       * @return The rpm.
       */
      @java.lang.Override
      public int getRpm() {
        return rpm_;
      }
      /**
       * <pre>
       * rotacao do motor, em rpm
       * </pre>
       *
       * <code>uint32 rpm = 4;</code>
       * @param value The rpm to set.
       * @return This builder for chaining.
       */
      public Builder setRpm(int value) {
        
        rpm_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * rotacao do motor, em rpm
       * </pre>
       *
       * <code>uint32 rpm = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRpm() {
        
        rpm_ = 0;
        onChanged();
        return this;
      }

      private int tempoViolacao_ ;
      /**
       * <pre>
       * tempo que o veiculo permaneceu em violacao dos parametros, em segundos
       * </pre>
       *
       * <code>uint32 tempoViolacao = 5;</code>
       * @return The tempoViolacao.
       */
      @java.lang.Override
      public int getTempoViolacao() {
        return tempoViolacao_;
      }
      /**
       * <pre>
       * tempo que o veiculo permaneceu em violacao dos parametros, em segundos
       * </pre>
       *
       * <code>uint32 tempoViolacao = 5;</code>
       * @param value The tempoViolacao to set.
       * @return This builder for chaining.
       */
      public Builder setTempoViolacao(int value) {
        
        tempoViolacao_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * tempo que o veiculo permaneceu em violacao dos parametros, em segundos
       * </pre>
       *
       * <code>uint32 tempoViolacao = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTempoViolacao() {
        
        tempoViolacao_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>double porcentagemCombustivel = 6;</code>
       * @return Whether the porcentagemCombustivel field is set.
       */
      public boolean hasPorcentagemCombustivel() {
        return combustivelCase_ == 6;
      }
      /**
       * <code>double porcentagemCombustivel = 6;</code>
       * @return The porcentagemCombustivel.
       */
      public double getPorcentagemCombustivel() {
        if (combustivelCase_ == 6) {
          return (java.lang.Double) combustivel_;
        }
        return 0D;
      }
      /**
       * <code>double porcentagemCombustivel = 6;</code>
       * @param value The porcentagemCombustivel to set.
       * @return This builder for chaining.
       */
      public Builder setPorcentagemCombustivel(double value) {
        combustivelCase_ = 6;
        combustivel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double porcentagemCombustivel = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPorcentagemCombustivel() {
        if (combustivelCase_ == 6) {
          combustivelCase_ = 0;
          combustivel_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>uint32 combustivelRestanteLitros = 7;</code>
       * @return Whether the combustivelRestanteLitros field is set.
       */
      public boolean hasCombustivelRestanteLitros() {
        return combustivelCase_ == 7;
      }
      /**
       * <code>uint32 combustivelRestanteLitros = 7;</code>
       * @return The combustivelRestanteLitros.
       */
      public int getCombustivelRestanteLitros() {
        if (combustivelCase_ == 7) {
          return (java.lang.Integer) combustivel_;
        }
        return 0;
      }
      /**
       * <code>uint32 combustivelRestanteLitros = 7;</code>
       * @param value The combustivelRestanteLitros to set.
       * @return This builder for chaining.
       */
      public Builder setCombustivelRestanteLitros(int value) {
        combustivelCase_ = 7;
        combustivel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 combustivelRestanteLitros = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCombustivelRestanteLitros() {
        if (combustivelCase_ == 7) {
          combustivelCase_ = 0;
          combustivel_ = null;
          onChanged();
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smgo.telemetria.EventoTelemetria)
    }

    // @@protoc_insertion_point(class_scope:smgo.telemetria.EventoTelemetria)
    private static final smgo.telemetria.Telemetria.EventoTelemetria DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smgo.telemetria.Telemetria.EventoTelemetria();
    }

    public static smgo.telemetria.Telemetria.EventoTelemetria getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EventoTelemetria>
        PARSER = new com.google.protobuf.AbstractParser<EventoTelemetria>() {
      @java.lang.Override
      public EventoTelemetria parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventoTelemetria(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EventoTelemetria> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventoTelemetria> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smgo.telemetria.Telemetria.EventoTelemetria getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MensagemTelemetriaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smgo.telemetria.MensagemTelemetria)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
     */
    java.util.List<smgo.telemetria.Telemetria.EventoTelemetria> 
        getEventosList();
    /**
     * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
     */
    smgo.telemetria.Telemetria.EventoTelemetria getEventos(int index);
    /**
     * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
     */
    int getEventosCount();
    /**
     * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
     */
    java.util.List<? extends smgo.telemetria.Telemetria.EventoTelemetriaOrBuilder> 
        getEventosOrBuilderList();
    /**
     * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
     */
    smgo.telemetria.Telemetria.EventoTelemetriaOrBuilder getEventosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code smgo.telemetria.MensagemTelemetria}
   */
  public static final class MensagemTelemetria extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smgo.telemetria.MensagemTelemetria)
      MensagemTelemetriaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MensagemTelemetria.newBuilder() to construct.
    private MensagemTelemetria(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MensagemTelemetria() {
      eventos_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MensagemTelemetria();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MensagemTelemetria(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                eventos_ = new java.util.ArrayList<smgo.telemetria.Telemetria.EventoTelemetria>();
                mutable_bitField0_ |= 0x00000001;
              }
              eventos_.add(
                  input.readMessage(smgo.telemetria.Telemetria.EventoTelemetria.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          eventos_ = java.util.Collections.unmodifiableList(eventos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smgo.telemetria.Telemetria.internal_static_smgo_telemetria_MensagemTelemetria_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smgo.telemetria.Telemetria.internal_static_smgo_telemetria_MensagemTelemetria_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smgo.telemetria.Telemetria.MensagemTelemetria.class, smgo.telemetria.Telemetria.MensagemTelemetria.Builder.class);
    }

    public static final int EVENTOS_FIELD_NUMBER = 1;
    private java.util.List<smgo.telemetria.Telemetria.EventoTelemetria> eventos_;
    /**
     * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
     */
    @java.lang.Override
    public java.util.List<smgo.telemetria.Telemetria.EventoTelemetria> getEventosList() {
      return eventos_;
    }
    /**
     * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends smgo.telemetria.Telemetria.EventoTelemetriaOrBuilder> 
        getEventosOrBuilderList() {
      return eventos_;
    }
    /**
     * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
     */
    @java.lang.Override
    public int getEventosCount() {
      return eventos_.size();
    }
    /**
     * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
     */
    @java.lang.Override
    public smgo.telemetria.Telemetria.EventoTelemetria getEventos(int index) {
      return eventos_.get(index);
    }
    /**
     * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
     */
    @java.lang.Override
    public smgo.telemetria.Telemetria.EventoTelemetriaOrBuilder getEventosOrBuilder(
        int index) {
      return eventos_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < eventos_.size(); i++) {
        output.writeMessage(1, eventos_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < eventos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, eventos_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smgo.telemetria.Telemetria.MensagemTelemetria)) {
        return super.equals(obj);
      }
      smgo.telemetria.Telemetria.MensagemTelemetria other = (smgo.telemetria.Telemetria.MensagemTelemetria) obj;

      if (!getEventosList()
          .equals(other.getEventosList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEventosCount() > 0) {
        hash = (37 * hash) + EVENTOS_FIELD_NUMBER;
        hash = (53 * hash) + getEventosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smgo.telemetria.Telemetria.MensagemTelemetria parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.telemetria.Telemetria.MensagemTelemetria parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.telemetria.Telemetria.MensagemTelemetria parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.telemetria.Telemetria.MensagemTelemetria parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.telemetria.Telemetria.MensagemTelemetria parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.telemetria.Telemetria.MensagemTelemetria parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.telemetria.Telemetria.MensagemTelemetria parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.telemetria.Telemetria.MensagemTelemetria parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.telemetria.Telemetria.MensagemTelemetria parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smgo.telemetria.Telemetria.MensagemTelemetria parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.telemetria.Telemetria.MensagemTelemetria parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.telemetria.Telemetria.MensagemTelemetria parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smgo.telemetria.Telemetria.MensagemTelemetria prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smgo.telemetria.MensagemTelemetria}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smgo.telemetria.MensagemTelemetria)
        smgo.telemetria.Telemetria.MensagemTelemetriaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smgo.telemetria.Telemetria.internal_static_smgo_telemetria_MensagemTelemetria_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smgo.telemetria.Telemetria.internal_static_smgo_telemetria_MensagemTelemetria_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smgo.telemetria.Telemetria.MensagemTelemetria.class, smgo.telemetria.Telemetria.MensagemTelemetria.Builder.class);
      }

      // Construct using smgo.telemetria.Telemetria.MensagemTelemetria.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEventosFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (eventosBuilder_ == null) {
          eventos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          eventosBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smgo.telemetria.Telemetria.internal_static_smgo_telemetria_MensagemTelemetria_descriptor;
      }

      @java.lang.Override
      public smgo.telemetria.Telemetria.MensagemTelemetria getDefaultInstanceForType() {
        return smgo.telemetria.Telemetria.MensagemTelemetria.getDefaultInstance();
      }

      @java.lang.Override
      public smgo.telemetria.Telemetria.MensagemTelemetria build() {
        smgo.telemetria.Telemetria.MensagemTelemetria result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smgo.telemetria.Telemetria.MensagemTelemetria buildPartial() {
        smgo.telemetria.Telemetria.MensagemTelemetria result = new smgo.telemetria.Telemetria.MensagemTelemetria(this);
        int from_bitField0_ = bitField0_;
        if (eventosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            eventos_ = java.util.Collections.unmodifiableList(eventos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.eventos_ = eventos_;
        } else {
          result.eventos_ = eventosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smgo.telemetria.Telemetria.MensagemTelemetria) {
          return mergeFrom((smgo.telemetria.Telemetria.MensagemTelemetria)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smgo.telemetria.Telemetria.MensagemTelemetria other) {
        if (other == smgo.telemetria.Telemetria.MensagemTelemetria.getDefaultInstance()) return this;
        if (eventosBuilder_ == null) {
          if (!other.eventos_.isEmpty()) {
            if (eventos_.isEmpty()) {
              eventos_ = other.eventos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEventosIsMutable();
              eventos_.addAll(other.eventos_);
            }
            onChanged();
          }
        } else {
          if (!other.eventos_.isEmpty()) {
            if (eventosBuilder_.isEmpty()) {
              eventosBuilder_.dispose();
              eventosBuilder_ = null;
              eventos_ = other.eventos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              eventosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEventosFieldBuilder() : null;
            } else {
              eventosBuilder_.addAllMessages(other.eventos_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smgo.telemetria.Telemetria.MensagemTelemetria parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smgo.telemetria.Telemetria.MensagemTelemetria) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<smgo.telemetria.Telemetria.EventoTelemetria> eventos_ =
        java.util.Collections.emptyList();
      private void ensureEventosIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          eventos_ = new java.util.ArrayList<smgo.telemetria.Telemetria.EventoTelemetria>(eventos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          smgo.telemetria.Telemetria.EventoTelemetria, smgo.telemetria.Telemetria.EventoTelemetria.Builder, smgo.telemetria.Telemetria.EventoTelemetriaOrBuilder> eventosBuilder_;

      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public java.util.List<smgo.telemetria.Telemetria.EventoTelemetria> getEventosList() {
        if (eventosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(eventos_);
        } else {
          return eventosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public int getEventosCount() {
        if (eventosBuilder_ == null) {
          return eventos_.size();
        } else {
          return eventosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public smgo.telemetria.Telemetria.EventoTelemetria getEventos(int index) {
        if (eventosBuilder_ == null) {
          return eventos_.get(index);
        } else {
          return eventosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public Builder setEventos(
          int index, smgo.telemetria.Telemetria.EventoTelemetria value) {
        if (eventosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventosIsMutable();
          eventos_.set(index, value);
          onChanged();
        } else {
          eventosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public Builder setEventos(
          int index, smgo.telemetria.Telemetria.EventoTelemetria.Builder builderForValue) {
        if (eventosBuilder_ == null) {
          ensureEventosIsMutable();
          eventos_.set(index, builderForValue.build());
          onChanged();
        } else {
          eventosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public Builder addEventos(smgo.telemetria.Telemetria.EventoTelemetria value) {
        if (eventosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventosIsMutable();
          eventos_.add(value);
          onChanged();
        } else {
          eventosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public Builder addEventos(
          int index, smgo.telemetria.Telemetria.EventoTelemetria value) {
        if (eventosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEventosIsMutable();
          eventos_.add(index, value);
          onChanged();
        } else {
          eventosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public Builder addEventos(
          smgo.telemetria.Telemetria.EventoTelemetria.Builder builderForValue) {
        if (eventosBuilder_ == null) {
          ensureEventosIsMutable();
          eventos_.add(builderForValue.build());
          onChanged();
        } else {
          eventosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public Builder addEventos(
          int index, smgo.telemetria.Telemetria.EventoTelemetria.Builder builderForValue) {
        if (eventosBuilder_ == null) {
          ensureEventosIsMutable();
          eventos_.add(index, builderForValue.build());
          onChanged();
        } else {
          eventosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public Builder addAllEventos(
          java.lang.Iterable<? extends smgo.telemetria.Telemetria.EventoTelemetria> values) {
        if (eventosBuilder_ == null) {
          ensureEventosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, eventos_);
          onChanged();
        } else {
          eventosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public Builder clearEventos() {
        if (eventosBuilder_ == null) {
          eventos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          eventosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public Builder removeEventos(int index) {
        if (eventosBuilder_ == null) {
          ensureEventosIsMutable();
          eventos_.remove(index);
          onChanged();
        } else {
          eventosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public smgo.telemetria.Telemetria.EventoTelemetria.Builder getEventosBuilder(
          int index) {
        return getEventosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public smgo.telemetria.Telemetria.EventoTelemetriaOrBuilder getEventosOrBuilder(
          int index) {
        if (eventosBuilder_ == null) {
          return eventos_.get(index);  } else {
          return eventosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public java.util.List<? extends smgo.telemetria.Telemetria.EventoTelemetriaOrBuilder> 
           getEventosOrBuilderList() {
        if (eventosBuilder_ != null) {
          return eventosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(eventos_);
        }
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public smgo.telemetria.Telemetria.EventoTelemetria.Builder addEventosBuilder() {
        return getEventosFieldBuilder().addBuilder(
            smgo.telemetria.Telemetria.EventoTelemetria.getDefaultInstance());
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public smgo.telemetria.Telemetria.EventoTelemetria.Builder addEventosBuilder(
          int index) {
        return getEventosFieldBuilder().addBuilder(
            index, smgo.telemetria.Telemetria.EventoTelemetria.getDefaultInstance());
      }
      /**
       * <code>repeated .smgo.telemetria.EventoTelemetria eventos = 1;</code>
       */
      public java.util.List<smgo.telemetria.Telemetria.EventoTelemetria.Builder> 
           getEventosBuilderList() {
        return getEventosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          smgo.telemetria.Telemetria.EventoTelemetria, smgo.telemetria.Telemetria.EventoTelemetria.Builder, smgo.telemetria.Telemetria.EventoTelemetriaOrBuilder> 
          getEventosFieldBuilder() {
        if (eventosBuilder_ == null) {
          eventosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              smgo.telemetria.Telemetria.EventoTelemetria, smgo.telemetria.Telemetria.EventoTelemetria.Builder, smgo.telemetria.Telemetria.EventoTelemetriaOrBuilder>(
                  eventos_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          eventos_ = null;
        }
        return eventosBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smgo.telemetria.MensagemTelemetria)
    }

    // @@protoc_insertion_point(class_scope:smgo.telemetria.MensagemTelemetria)
    private static final smgo.telemetria.Telemetria.MensagemTelemetria DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smgo.telemetria.Telemetria.MensagemTelemetria();
    }

    public static smgo.telemetria.Telemetria.MensagemTelemetria getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MensagemTelemetria>
        PARSER = new com.google.protobuf.AbstractParser<MensagemTelemetria>() {
      @java.lang.Override
      public MensagemTelemetria parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MensagemTelemetria(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MensagemTelemetria> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MensagemTelemetria> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smgo.telemetria.Telemetria.MensagemTelemetria getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smgo_telemetria_EventoTelemetria_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smgo_telemetria_EventoTelemetria_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smgo_telemetria_MensagemTelemetria_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smgo_telemetria_MensagemTelemetria_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020telemetria.proto\022\017smgo.telemetria\032\013com" +
      "um.proto\032\024posicionamento.proto\"\366\002\n\020Event" +
      "oTelemetria\022\033\n\023identificadorEvento\030\001 \001(\r" +
      "\022-\n\007posicao\030\002 \001(\0132\034.smgo.posicao.Posicio" +
      "namento\022\022\n\naceleracao\030\003 \001(\001\022\013\n\003rpm\030\004 \001(\r" +
      "\022\025\n\rtempoViolacao\030\005 \001(\r\022 \n\026porcentagemCo" +
      "mbustivel\030\006 \001(\001H\000\022#\n\031combustivelRestante" +
      "Litros\030\007 \001(\rH\000\"\207\001\n\024TipoEventoTelemetria\022" +
      "\025\n\021ACELERACAO_BRUSCA\020\000\022\021\n\rFREADA_BRUSCA\020" +
      "\001\022\020\n\014CURVA_BRUSCA\020\002\022\034\n\030ROTACAO_FORA_FAIX" +
      "A_IDEAL\020\003\022\025\n\021DADOS_COMBUSTIVEL\020\004B\r\n\013comb" +
      "ustivel\"H\n\022MensagemTelemetria\0222\n\007eventos" +
      "\030\001 \003(\0132!.smgo.telemetria.EventoTelemetri" +
      "ab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          smgo.Comum.getDescriptor(),
          smgo.posicao.PosicionamentoOuterClass.getDescriptor(),
        });
    internal_static_smgo_telemetria_EventoTelemetria_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smgo_telemetria_EventoTelemetria_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smgo_telemetria_EventoTelemetria_descriptor,
        new java.lang.String[] { "IdentificadorEvento", "Posicao", "Aceleracao", "Rpm", "TempoViolacao", "PorcentagemCombustivel", "CombustivelRestanteLitros", "Combustivel", });
    internal_static_smgo_telemetria_MensagemTelemetria_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smgo_telemetria_MensagemTelemetria_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smgo_telemetria_MensagemTelemetria_descriptor,
        new java.lang.String[] { "Eventos", });
    smgo.Comum.getDescriptor();
    smgo.posicao.PosicionamentoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
