// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem.proto

package smgo.mensagem;

public final class Mensagem {
  private Mensagem() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MensagemTextoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smgo.mensagem.MensagemTexto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Identificador da mensagem de texto
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <pre>
     * Conteúdo, caso a mensagem de texto não tenha identificador
     * </pre>
     *
     * <code>string texto = 2;</code>
     * @return The texto.
     */
    java.lang.String getTexto();
    /**
     * <pre>
     * Conteúdo, caso a mensagem de texto não tenha identificador
     * </pre>
     *
     * <code>string texto = 2;</code>
     * @return The bytes for texto.
     */
    com.google.protobuf.ByteString
        getTextoBytes();
  }
  /**
   * Protobuf type {@code smgo.mensagem.MensagemTexto}
   */
  public static final class MensagemTexto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smgo.mensagem.MensagemTexto)
      MensagemTextoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MensagemTexto.newBuilder() to construct.
    private MensagemTexto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MensagemTexto() {
      texto_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MensagemTexto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MensagemTexto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              texto_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smgo.mensagem.Mensagem.internal_static_smgo_mensagem_MensagemTexto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smgo.mensagem.Mensagem.internal_static_smgo_mensagem_MensagemTexto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smgo.mensagem.Mensagem.MensagemTexto.class, smgo.mensagem.Mensagem.MensagemTexto.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * Identificador da mensagem de texto
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int TEXTO_FIELD_NUMBER = 2;
    private volatile java.lang.Object texto_;
    /**
     * <pre>
     * Conteúdo, caso a mensagem de texto não tenha identificador
     * </pre>
     *
     * <code>string texto = 2;</code>
     * @return The texto.
     */
    @java.lang.Override
    public java.lang.String getTexto() {
      java.lang.Object ref = texto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        texto_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Conteúdo, caso a mensagem de texto não tenha identificador
     * </pre>
     *
     * <code>string texto = 2;</code>
     * @return The bytes for texto.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextoBytes() {
      java.lang.Object ref = texto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        texto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(texto_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, texto_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(texto_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, texto_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smgo.mensagem.Mensagem.MensagemTexto)) {
        return super.equals(obj);
      }
      smgo.mensagem.Mensagem.MensagemTexto other = (smgo.mensagem.Mensagem.MensagemTexto) obj;

      if (getId()
          != other.getId()) return false;
      if (!getTexto()
          .equals(other.getTexto())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TEXTO_FIELD_NUMBER;
      hash = (53 * hash) + getTexto().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smgo.mensagem.Mensagem.MensagemTexto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.mensagem.Mensagem.MensagemTexto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.mensagem.Mensagem.MensagemTexto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.mensagem.Mensagem.MensagemTexto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.mensagem.Mensagem.MensagemTexto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.mensagem.Mensagem.MensagemTexto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.mensagem.Mensagem.MensagemTexto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.mensagem.Mensagem.MensagemTexto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.mensagem.Mensagem.MensagemTexto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smgo.mensagem.Mensagem.MensagemTexto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.mensagem.Mensagem.MensagemTexto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.mensagem.Mensagem.MensagemTexto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smgo.mensagem.Mensagem.MensagemTexto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smgo.mensagem.MensagemTexto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smgo.mensagem.MensagemTexto)
        smgo.mensagem.Mensagem.MensagemTextoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smgo.mensagem.Mensagem.internal_static_smgo_mensagem_MensagemTexto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smgo.mensagem.Mensagem.internal_static_smgo_mensagem_MensagemTexto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smgo.mensagem.Mensagem.MensagemTexto.class, smgo.mensagem.Mensagem.MensagemTexto.Builder.class);
      }

      // Construct using smgo.mensagem.Mensagem.MensagemTexto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        texto_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smgo.mensagem.Mensagem.internal_static_smgo_mensagem_MensagemTexto_descriptor;
      }

      @java.lang.Override
      public smgo.mensagem.Mensagem.MensagemTexto getDefaultInstanceForType() {
        return smgo.mensagem.Mensagem.MensagemTexto.getDefaultInstance();
      }

      @java.lang.Override
      public smgo.mensagem.Mensagem.MensagemTexto build() {
        smgo.mensagem.Mensagem.MensagemTexto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smgo.mensagem.Mensagem.MensagemTexto buildPartial() {
        smgo.mensagem.Mensagem.MensagemTexto result = new smgo.mensagem.Mensagem.MensagemTexto(this);
        result.id_ = id_;
        result.texto_ = texto_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smgo.mensagem.Mensagem.MensagemTexto) {
          return mergeFrom((smgo.mensagem.Mensagem.MensagemTexto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smgo.mensagem.Mensagem.MensagemTexto other) {
        if (other == smgo.mensagem.Mensagem.MensagemTexto.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getTexto().isEmpty()) {
          texto_ = other.texto_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smgo.mensagem.Mensagem.MensagemTexto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smgo.mensagem.Mensagem.MensagemTexto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       * Identificador da mensagem de texto
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * Identificador da mensagem de texto
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Identificador da mensagem de texto
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object texto_ = "";
      /**
       * <pre>
       * Conteúdo, caso a mensagem de texto não tenha identificador
       * </pre>
       *
       * <code>string texto = 2;</code>
       * @return The texto.
       */
      public java.lang.String getTexto() {
        java.lang.Object ref = texto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          texto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Conteúdo, caso a mensagem de texto não tenha identificador
       * </pre>
       *
       * <code>string texto = 2;</code>
       * @return The bytes for texto.
       */
      public com.google.protobuf.ByteString
          getTextoBytes() {
        java.lang.Object ref = texto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          texto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Conteúdo, caso a mensagem de texto não tenha identificador
       * </pre>
       *
       * <code>string texto = 2;</code>
       * @param value The texto to set.
       * @return This builder for chaining.
       */
      public Builder setTexto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        texto_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Conteúdo, caso a mensagem de texto não tenha identificador
       * </pre>
       *
       * <code>string texto = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTexto() {
        
        texto_ = getDefaultInstance().getTexto();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Conteúdo, caso a mensagem de texto não tenha identificador
       * </pre>
       *
       * <code>string texto = 2;</code>
       * @param value The bytes for texto to set.
       * @return This builder for chaining.
       */
      public Builder setTextoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        texto_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smgo.mensagem.MensagemTexto)
    }

    // @@protoc_insertion_point(class_scope:smgo.mensagem.MensagemTexto)
    private static final smgo.mensagem.Mensagem.MensagemTexto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smgo.mensagem.Mensagem.MensagemTexto();
    }

    public static smgo.mensagem.Mensagem.MensagemTexto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MensagemTexto>
        PARSER = new com.google.protobuf.AbstractParser<MensagemTexto>() {
      @java.lang.Override
      public MensagemTexto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MensagemTexto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MensagemTexto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MensagemTexto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smgo.mensagem.Mensagem.MensagemTexto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MensagemAudioOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smgo.mensagem.MensagemAudio)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Bytes do áudio
     * </pre>
     *
     * <code>bytes audio = 1;</code>
     * @return The audio.
     */
    com.google.protobuf.ByteString getAudio();
  }
  /**
   * Protobuf type {@code smgo.mensagem.MensagemAudio}
   */
  public static final class MensagemAudio extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smgo.mensagem.MensagemAudio)
      MensagemAudioOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MensagemAudio.newBuilder() to construct.
    private MensagemAudio(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MensagemAudio() {
      audio_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MensagemAudio();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MensagemAudio(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              audio_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smgo.mensagem.Mensagem.internal_static_smgo_mensagem_MensagemAudio_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smgo.mensagem.Mensagem.internal_static_smgo_mensagem_MensagemAudio_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smgo.mensagem.Mensagem.MensagemAudio.class, smgo.mensagem.Mensagem.MensagemAudio.Builder.class);
    }

    public static final int AUDIO_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString audio_;
    /**
     * <pre>
     * Bytes do áudio
     * </pre>
     *
     * <code>bytes audio = 1;</code>
     * @return The audio.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAudio() {
      return audio_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!audio_.isEmpty()) {
        output.writeBytes(1, audio_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!audio_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, audio_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smgo.mensagem.Mensagem.MensagemAudio)) {
        return super.equals(obj);
      }
      smgo.mensagem.Mensagem.MensagemAudio other = (smgo.mensagem.Mensagem.MensagemAudio) obj;

      if (!getAudio()
          .equals(other.getAudio())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AUDIO_FIELD_NUMBER;
      hash = (53 * hash) + getAudio().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smgo.mensagem.Mensagem.MensagemAudio parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.mensagem.Mensagem.MensagemAudio parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.mensagem.Mensagem.MensagemAudio parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.mensagem.Mensagem.MensagemAudio parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.mensagem.Mensagem.MensagemAudio parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.mensagem.Mensagem.MensagemAudio parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.mensagem.Mensagem.MensagemAudio parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.mensagem.Mensagem.MensagemAudio parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.mensagem.Mensagem.MensagemAudio parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smgo.mensagem.Mensagem.MensagemAudio parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.mensagem.Mensagem.MensagemAudio parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.mensagem.Mensagem.MensagemAudio parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smgo.mensagem.Mensagem.MensagemAudio prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smgo.mensagem.MensagemAudio}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smgo.mensagem.MensagemAudio)
        smgo.mensagem.Mensagem.MensagemAudioOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smgo.mensagem.Mensagem.internal_static_smgo_mensagem_MensagemAudio_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smgo.mensagem.Mensagem.internal_static_smgo_mensagem_MensagemAudio_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smgo.mensagem.Mensagem.MensagemAudio.class, smgo.mensagem.Mensagem.MensagemAudio.Builder.class);
      }

      // Construct using smgo.mensagem.Mensagem.MensagemAudio.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        audio_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smgo.mensagem.Mensagem.internal_static_smgo_mensagem_MensagemAudio_descriptor;
      }

      @java.lang.Override
      public smgo.mensagem.Mensagem.MensagemAudio getDefaultInstanceForType() {
        return smgo.mensagem.Mensagem.MensagemAudio.getDefaultInstance();
      }

      @java.lang.Override
      public smgo.mensagem.Mensagem.MensagemAudio build() {
        smgo.mensagem.Mensagem.MensagemAudio result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smgo.mensagem.Mensagem.MensagemAudio buildPartial() {
        smgo.mensagem.Mensagem.MensagemAudio result = new smgo.mensagem.Mensagem.MensagemAudio(this);
        result.audio_ = audio_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smgo.mensagem.Mensagem.MensagemAudio) {
          return mergeFrom((smgo.mensagem.Mensagem.MensagemAudio)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smgo.mensagem.Mensagem.MensagemAudio other) {
        if (other == smgo.mensagem.Mensagem.MensagemAudio.getDefaultInstance()) return this;
        if (other.getAudio() != com.google.protobuf.ByteString.EMPTY) {
          setAudio(other.getAudio());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smgo.mensagem.Mensagem.MensagemAudio parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smgo.mensagem.Mensagem.MensagemAudio) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString audio_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Bytes do áudio
       * </pre>
       *
       * <code>bytes audio = 1;</code>
       * @return The audio.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAudio() {
        return audio_;
      }
      /**
       * <pre>
       * Bytes do áudio
       * </pre>
       *
       * <code>bytes audio = 1;</code>
       * @param value The audio to set.
       * @return This builder for chaining.
       */
      public Builder setAudio(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        audio_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Bytes do áudio
       * </pre>
       *
       * <code>bytes audio = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAudio() {
        
        audio_ = getDefaultInstance().getAudio();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smgo.mensagem.MensagemAudio)
    }

    // @@protoc_insertion_point(class_scope:smgo.mensagem.MensagemAudio)
    private static final smgo.mensagem.Mensagem.MensagemAudio DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smgo.mensagem.Mensagem.MensagemAudio();
    }

    public static smgo.mensagem.Mensagem.MensagemAudio getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MensagemAudio>
        PARSER = new com.google.protobuf.AbstractParser<MensagemAudio>() {
      @java.lang.Override
      public MensagemAudio parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MensagemAudio(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MensagemAudio> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MensagemAudio> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smgo.mensagem.Mensagem.MensagemAudio getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EnvioMensagemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smgo.mensagem.EnvioMensagem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * mensagem de texto
     * </pre>
     *
     * <code>.smgo.mensagem.MensagemTexto mensagemTexto = 5;</code>
     * @return Whether the mensagemTexto field is set.
     */
    boolean hasMensagemTexto();
    /**
     * <pre>
     * mensagem de texto
     * </pre>
     *
     * <code>.smgo.mensagem.MensagemTexto mensagemTexto = 5;</code>
     * @return The mensagemTexto.
     */
    smgo.mensagem.Mensagem.MensagemTexto getMensagemTexto();
    /**
     * <pre>
     * mensagem de texto
     * </pre>
     *
     * <code>.smgo.mensagem.MensagemTexto mensagemTexto = 5;</code>
     */
    smgo.mensagem.Mensagem.MensagemTextoOrBuilder getMensagemTextoOrBuilder();

    /**
     * <code>.smgo.mensagem.MensagemAudio mensagemAudio = 6;</code>
     * @return Whether the mensagemAudio field is set.
     */
    boolean hasMensagemAudio();
    /**
     * <code>.smgo.mensagem.MensagemAudio mensagemAudio = 6;</code>
     * @return The mensagemAudio.
     */
    smgo.mensagem.Mensagem.MensagemAudio getMensagemAudio();
    /**
     * <code>.smgo.mensagem.MensagemAudio mensagemAudio = 6;</code>
     */
    smgo.mensagem.Mensagem.MensagemAudioOrBuilder getMensagemAudioOrBuilder();

    /**
     * <pre>
     * comentario adicional
     * </pre>
     *
     * <code>string comentariosAdicionais = 4;</code>
     * @return The comentariosAdicionais.
     */
    java.lang.String getComentariosAdicionais();
    /**
     * <pre>
     * comentario adicional
     * </pre>
     *
     * <code>string comentariosAdicionais = 4;</code>
     * @return The bytes for comentariosAdicionais.
     */
    com.google.protobuf.ByteString
        getComentariosAdicionaisBytes();

    /**
     * <pre>
     * Última posição do veículo quando a mensagem foi gerada
     * </pre>
     *
     * <code>.smgo.posicao.Posicionamento ultimaPosicao = 7;</code>
     * @return Whether the ultimaPosicao field is set.
     */
    boolean hasUltimaPosicao();
    /**
     * <pre>
     * Última posição do veículo quando a mensagem foi gerada
     * </pre>
     *
     * <code>.smgo.posicao.Posicionamento ultimaPosicao = 7;</code>
     * @return The ultimaPosicao.
     */
    smgo.posicao.PosicionamentoOuterClass.Posicionamento getUltimaPosicao();
    /**
     * <pre>
     * Última posição do veículo quando a mensagem foi gerada
     * </pre>
     *
     * <code>.smgo.posicao.Posicionamento ultimaPosicao = 7;</code>
     */
    smgo.posicao.PosicionamentoOuterClass.PosicionamentoOrBuilder getUltimaPosicaoOrBuilder();

    /**
     * <pre>
     * Chapa do motorista que enviou a mensagem
     * </pre>
     *
     * <code>string chapaMotorista = 8;</code>
     * @return The chapaMotorista.
     */
    java.lang.String getChapaMotorista();
    /**
     * <pre>
     * Chapa do motorista que enviou a mensagem
     * </pre>
     *
     * <code>string chapaMotorista = 8;</code>
     * @return The bytes for chapaMotorista.
     */
    com.google.protobuf.ByteString
        getChapaMotoristaBytes();

    public smgo.mensagem.Mensagem.EnvioMensagem.MensagemCase getMensagemCase();
  }
  /**
   * <pre>
   * mensagens de audio, texto
   * </pre>
   *
   * Protobuf type {@code smgo.mensagem.EnvioMensagem}
   */
  public static final class EnvioMensagem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smgo.mensagem.EnvioMensagem)
      EnvioMensagemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EnvioMensagem.newBuilder() to construct.
    private EnvioMensagem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EnvioMensagem() {
      comentariosAdicionais_ = "";
      chapaMotorista_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EnvioMensagem();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EnvioMensagem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              comentariosAdicionais_ = s;
              break;
            }
            case 42: {
              smgo.mensagem.Mensagem.MensagemTexto.Builder subBuilder = null;
              if (mensagemCase_ == 5) {
                subBuilder = ((smgo.mensagem.Mensagem.MensagemTexto) mensagem_).toBuilder();
              }
              mensagem_ =
                  input.readMessage(smgo.mensagem.Mensagem.MensagemTexto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((smgo.mensagem.Mensagem.MensagemTexto) mensagem_);
                mensagem_ = subBuilder.buildPartial();
              }
              mensagemCase_ = 5;
              break;
            }
            case 50: {
              smgo.mensagem.Mensagem.MensagemAudio.Builder subBuilder = null;
              if (mensagemCase_ == 6) {
                subBuilder = ((smgo.mensagem.Mensagem.MensagemAudio) mensagem_).toBuilder();
              }
              mensagem_ =
                  input.readMessage(smgo.mensagem.Mensagem.MensagemAudio.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((smgo.mensagem.Mensagem.MensagemAudio) mensagem_);
                mensagem_ = subBuilder.buildPartial();
              }
              mensagemCase_ = 6;
              break;
            }
            case 58: {
              smgo.posicao.PosicionamentoOuterClass.Posicionamento.Builder subBuilder = null;
              if (ultimaPosicao_ != null) {
                subBuilder = ultimaPosicao_.toBuilder();
              }
              ultimaPosicao_ = input.readMessage(smgo.posicao.PosicionamentoOuterClass.Posicionamento.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ultimaPosicao_);
                ultimaPosicao_ = subBuilder.buildPartial();
              }

              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              chapaMotorista_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smgo.mensagem.Mensagem.internal_static_smgo_mensagem_EnvioMensagem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smgo.mensagem.Mensagem.internal_static_smgo_mensagem_EnvioMensagem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smgo.mensagem.Mensagem.EnvioMensagem.class, smgo.mensagem.Mensagem.EnvioMensagem.Builder.class);
    }

    private int mensagemCase_ = 0;
    private java.lang.Object mensagem_;
    public enum MensagemCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      MENSAGEMTEXTO(5),
      MENSAGEMAUDIO(6),
      MENSAGEM_NOT_SET(0);
      private final int value;
      private MensagemCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MensagemCase valueOf(int value) {
        return forNumber(value);
      }

      public static MensagemCase forNumber(int value) {
        switch (value) {
          case 5: return MENSAGEMTEXTO;
          case 6: return MENSAGEMAUDIO;
          case 0: return MENSAGEM_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MensagemCase
    getMensagemCase() {
      return MensagemCase.forNumber(
          mensagemCase_);
    }

    public static final int MENSAGEMTEXTO_FIELD_NUMBER = 5;
    /**
     * <pre>
     * mensagem de texto
     * </pre>
     *
     * <code>.smgo.mensagem.MensagemTexto mensagemTexto = 5;</code>
     * @return Whether the mensagemTexto field is set.
     */
    @java.lang.Override
    public boolean hasMensagemTexto() {
      return mensagemCase_ == 5;
    }
    /**
     * <pre>
     * mensagem de texto
     * </pre>
     *
     * <code>.smgo.mensagem.MensagemTexto mensagemTexto = 5;</code>
     * @return The mensagemTexto.
     */
    @java.lang.Override
    public smgo.mensagem.Mensagem.MensagemTexto getMensagemTexto() {
      if (mensagemCase_ == 5) {
         return (smgo.mensagem.Mensagem.MensagemTexto) mensagem_;
      }
      return smgo.mensagem.Mensagem.MensagemTexto.getDefaultInstance();
    }
    /**
     * <pre>
     * mensagem de texto
     * </pre>
     *
     * <code>.smgo.mensagem.MensagemTexto mensagemTexto = 5;</code>
     */
    @java.lang.Override
    public smgo.mensagem.Mensagem.MensagemTextoOrBuilder getMensagemTextoOrBuilder() {
      if (mensagemCase_ == 5) {
         return (smgo.mensagem.Mensagem.MensagemTexto) mensagem_;
      }
      return smgo.mensagem.Mensagem.MensagemTexto.getDefaultInstance();
    }

    public static final int MENSAGEMAUDIO_FIELD_NUMBER = 6;
    /**
     * <code>.smgo.mensagem.MensagemAudio mensagemAudio = 6;</code>
     * @return Whether the mensagemAudio field is set.
     */
    @java.lang.Override
    public boolean hasMensagemAudio() {
      return mensagemCase_ == 6;
    }
    /**
     * <code>.smgo.mensagem.MensagemAudio mensagemAudio = 6;</code>
     * @return The mensagemAudio.
     */
    @java.lang.Override
    public smgo.mensagem.Mensagem.MensagemAudio getMensagemAudio() {
      if (mensagemCase_ == 6) {
         return (smgo.mensagem.Mensagem.MensagemAudio) mensagem_;
      }
      return smgo.mensagem.Mensagem.MensagemAudio.getDefaultInstance();
    }
    /**
     * <code>.smgo.mensagem.MensagemAudio mensagemAudio = 6;</code>
     */
    @java.lang.Override
    public smgo.mensagem.Mensagem.MensagemAudioOrBuilder getMensagemAudioOrBuilder() {
      if (mensagemCase_ == 6) {
         return (smgo.mensagem.Mensagem.MensagemAudio) mensagem_;
      }
      return smgo.mensagem.Mensagem.MensagemAudio.getDefaultInstance();
    }

    public static final int COMENTARIOSADICIONAIS_FIELD_NUMBER = 4;
    private volatile java.lang.Object comentariosAdicionais_;
    /**
     * <pre>
     * comentario adicional
     * </pre>
     *
     * <code>string comentariosAdicionais = 4;</code>
     * @return The comentariosAdicionais.
     */
    @java.lang.Override
    public java.lang.String getComentariosAdicionais() {
      java.lang.Object ref = comentariosAdicionais_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comentariosAdicionais_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * comentario adicional
     * </pre>
     *
     * <code>string comentariosAdicionais = 4;</code>
     * @return The bytes for comentariosAdicionais.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getComentariosAdicionaisBytes() {
      java.lang.Object ref = comentariosAdicionais_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comentariosAdicionais_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ULTIMAPOSICAO_FIELD_NUMBER = 7;
    private smgo.posicao.PosicionamentoOuterClass.Posicionamento ultimaPosicao_;
    /**
     * <pre>
     * Última posição do veículo quando a mensagem foi gerada
     * </pre>
     *
     * <code>.smgo.posicao.Posicionamento ultimaPosicao = 7;</code>
     * @return Whether the ultimaPosicao field is set.
     */
    @java.lang.Override
    public boolean hasUltimaPosicao() {
      return ultimaPosicao_ != null;
    }
    /**
     * <pre>
     * Última posição do veículo quando a mensagem foi gerada
     * </pre>
     *
     * <code>.smgo.posicao.Posicionamento ultimaPosicao = 7;</code>
     * @return The ultimaPosicao.
     */
    @java.lang.Override
    public smgo.posicao.PosicionamentoOuterClass.Posicionamento getUltimaPosicao() {
      return ultimaPosicao_ == null ? smgo.posicao.PosicionamentoOuterClass.Posicionamento.getDefaultInstance() : ultimaPosicao_;
    }
    /**
     * <pre>
     * Última posição do veículo quando a mensagem foi gerada
     * </pre>
     *
     * <code>.smgo.posicao.Posicionamento ultimaPosicao = 7;</code>
     */
    @java.lang.Override
    public smgo.posicao.PosicionamentoOuterClass.PosicionamentoOrBuilder getUltimaPosicaoOrBuilder() {
      return getUltimaPosicao();
    }

    public static final int CHAPAMOTORISTA_FIELD_NUMBER = 8;
    private volatile java.lang.Object chapaMotorista_;
    /**
     * <pre>
     * Chapa do motorista que enviou a mensagem
     * </pre>
     *
     * <code>string chapaMotorista = 8;</code>
     * @return The chapaMotorista.
     */
    @java.lang.Override
    public java.lang.String getChapaMotorista() {
      java.lang.Object ref = chapaMotorista_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chapaMotorista_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Chapa do motorista que enviou a mensagem
     * </pre>
     *
     * <code>string chapaMotorista = 8;</code>
     * @return The bytes for chapaMotorista.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChapaMotoristaBytes() {
      java.lang.Object ref = chapaMotorista_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chapaMotorista_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(comentariosAdicionais_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, comentariosAdicionais_);
      }
      if (mensagemCase_ == 5) {
        output.writeMessage(5, (smgo.mensagem.Mensagem.MensagemTexto) mensagem_);
      }
      if (mensagemCase_ == 6) {
        output.writeMessage(6, (smgo.mensagem.Mensagem.MensagemAudio) mensagem_);
      }
      if (ultimaPosicao_ != null) {
        output.writeMessage(7, getUltimaPosicao());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chapaMotorista_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, chapaMotorista_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(comentariosAdicionais_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, comentariosAdicionais_);
      }
      if (mensagemCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (smgo.mensagem.Mensagem.MensagemTexto) mensagem_);
      }
      if (mensagemCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (smgo.mensagem.Mensagem.MensagemAudio) mensagem_);
      }
      if (ultimaPosicao_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getUltimaPosicao());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chapaMotorista_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, chapaMotorista_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smgo.mensagem.Mensagem.EnvioMensagem)) {
        return super.equals(obj);
      }
      smgo.mensagem.Mensagem.EnvioMensagem other = (smgo.mensagem.Mensagem.EnvioMensagem) obj;

      if (!getComentariosAdicionais()
          .equals(other.getComentariosAdicionais())) return false;
      if (hasUltimaPosicao() != other.hasUltimaPosicao()) return false;
      if (hasUltimaPosicao()) {
        if (!getUltimaPosicao()
            .equals(other.getUltimaPosicao())) return false;
      }
      if (!getChapaMotorista()
          .equals(other.getChapaMotorista())) return false;
      if (!getMensagemCase().equals(other.getMensagemCase())) return false;
      switch (mensagemCase_) {
        case 5:
          if (!getMensagemTexto()
              .equals(other.getMensagemTexto())) return false;
          break;
        case 6:
          if (!getMensagemAudio()
              .equals(other.getMensagemAudio())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMENTARIOSADICIONAIS_FIELD_NUMBER;
      hash = (53 * hash) + getComentariosAdicionais().hashCode();
      if (hasUltimaPosicao()) {
        hash = (37 * hash) + ULTIMAPOSICAO_FIELD_NUMBER;
        hash = (53 * hash) + getUltimaPosicao().hashCode();
      }
      hash = (37 * hash) + CHAPAMOTORISTA_FIELD_NUMBER;
      hash = (53 * hash) + getChapaMotorista().hashCode();
      switch (mensagemCase_) {
        case 5:
          hash = (37 * hash) + MENSAGEMTEXTO_FIELD_NUMBER;
          hash = (53 * hash) + getMensagemTexto().hashCode();
          break;
        case 6:
          hash = (37 * hash) + MENSAGEMAUDIO_FIELD_NUMBER;
          hash = (53 * hash) + getMensagemAudio().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smgo.mensagem.Mensagem.EnvioMensagem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.mensagem.Mensagem.EnvioMensagem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.mensagem.Mensagem.EnvioMensagem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.mensagem.Mensagem.EnvioMensagem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.mensagem.Mensagem.EnvioMensagem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.mensagem.Mensagem.EnvioMensagem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.mensagem.Mensagem.EnvioMensagem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.mensagem.Mensagem.EnvioMensagem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.mensagem.Mensagem.EnvioMensagem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smgo.mensagem.Mensagem.EnvioMensagem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.mensagem.Mensagem.EnvioMensagem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.mensagem.Mensagem.EnvioMensagem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smgo.mensagem.Mensagem.EnvioMensagem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * mensagens de audio, texto
     * </pre>
     *
     * Protobuf type {@code smgo.mensagem.EnvioMensagem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smgo.mensagem.EnvioMensagem)
        smgo.mensagem.Mensagem.EnvioMensagemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smgo.mensagem.Mensagem.internal_static_smgo_mensagem_EnvioMensagem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smgo.mensagem.Mensagem.internal_static_smgo_mensagem_EnvioMensagem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smgo.mensagem.Mensagem.EnvioMensagem.class, smgo.mensagem.Mensagem.EnvioMensagem.Builder.class);
      }

      // Construct using smgo.mensagem.Mensagem.EnvioMensagem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        comentariosAdicionais_ = "";

        if (ultimaPosicaoBuilder_ == null) {
          ultimaPosicao_ = null;
        } else {
          ultimaPosicao_ = null;
          ultimaPosicaoBuilder_ = null;
        }
        chapaMotorista_ = "";

        mensagemCase_ = 0;
        mensagem_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smgo.mensagem.Mensagem.internal_static_smgo_mensagem_EnvioMensagem_descriptor;
      }

      @java.lang.Override
      public smgo.mensagem.Mensagem.EnvioMensagem getDefaultInstanceForType() {
        return smgo.mensagem.Mensagem.EnvioMensagem.getDefaultInstance();
      }

      @java.lang.Override
      public smgo.mensagem.Mensagem.EnvioMensagem build() {
        smgo.mensagem.Mensagem.EnvioMensagem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smgo.mensagem.Mensagem.EnvioMensagem buildPartial() {
        smgo.mensagem.Mensagem.EnvioMensagem result = new smgo.mensagem.Mensagem.EnvioMensagem(this);
        if (mensagemCase_ == 5) {
          if (mensagemTextoBuilder_ == null) {
            result.mensagem_ = mensagem_;
          } else {
            result.mensagem_ = mensagemTextoBuilder_.build();
          }
        }
        if (mensagemCase_ == 6) {
          if (mensagemAudioBuilder_ == null) {
            result.mensagem_ = mensagem_;
          } else {
            result.mensagem_ = mensagemAudioBuilder_.build();
          }
        }
        result.comentariosAdicionais_ = comentariosAdicionais_;
        if (ultimaPosicaoBuilder_ == null) {
          result.ultimaPosicao_ = ultimaPosicao_;
        } else {
          result.ultimaPosicao_ = ultimaPosicaoBuilder_.build();
        }
        result.chapaMotorista_ = chapaMotorista_;
        result.mensagemCase_ = mensagemCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smgo.mensagem.Mensagem.EnvioMensagem) {
          return mergeFrom((smgo.mensagem.Mensagem.EnvioMensagem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smgo.mensagem.Mensagem.EnvioMensagem other) {
        if (other == smgo.mensagem.Mensagem.EnvioMensagem.getDefaultInstance()) return this;
        if (!other.getComentariosAdicionais().isEmpty()) {
          comentariosAdicionais_ = other.comentariosAdicionais_;
          onChanged();
        }
        if (other.hasUltimaPosicao()) {
          mergeUltimaPosicao(other.getUltimaPosicao());
        }
        if (!other.getChapaMotorista().isEmpty()) {
          chapaMotorista_ = other.chapaMotorista_;
          onChanged();
        }
        switch (other.getMensagemCase()) {
          case MENSAGEMTEXTO: {
            mergeMensagemTexto(other.getMensagemTexto());
            break;
          }
          case MENSAGEMAUDIO: {
            mergeMensagemAudio(other.getMensagemAudio());
            break;
          }
          case MENSAGEM_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smgo.mensagem.Mensagem.EnvioMensagem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smgo.mensagem.Mensagem.EnvioMensagem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int mensagemCase_ = 0;
      private java.lang.Object mensagem_;
      public MensagemCase
          getMensagemCase() {
        return MensagemCase.forNumber(
            mensagemCase_);
      }

      public Builder clearMensagem() {
        mensagemCase_ = 0;
        mensagem_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          smgo.mensagem.Mensagem.MensagemTexto, smgo.mensagem.Mensagem.MensagemTexto.Builder, smgo.mensagem.Mensagem.MensagemTextoOrBuilder> mensagemTextoBuilder_;
      /**
       * <pre>
       * mensagem de texto
       * </pre>
       *
       * <code>.smgo.mensagem.MensagemTexto mensagemTexto = 5;</code>
       * @return Whether the mensagemTexto field is set.
       */
      @java.lang.Override
      public boolean hasMensagemTexto() {
        return mensagemCase_ == 5;
      }
      /**
       * <pre>
       * mensagem de texto
       * </pre>
       *
       * <code>.smgo.mensagem.MensagemTexto mensagemTexto = 5;</code>
       * @return The mensagemTexto.
       */
      @java.lang.Override
      public smgo.mensagem.Mensagem.MensagemTexto getMensagemTexto() {
        if (mensagemTextoBuilder_ == null) {
          if (mensagemCase_ == 5) {
            return (smgo.mensagem.Mensagem.MensagemTexto) mensagem_;
          }
          return smgo.mensagem.Mensagem.MensagemTexto.getDefaultInstance();
        } else {
          if (mensagemCase_ == 5) {
            return mensagemTextoBuilder_.getMessage();
          }
          return smgo.mensagem.Mensagem.MensagemTexto.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * mensagem de texto
       * </pre>
       *
       * <code>.smgo.mensagem.MensagemTexto mensagemTexto = 5;</code>
       */
      public Builder setMensagemTexto(smgo.mensagem.Mensagem.MensagemTexto value) {
        if (mensagemTextoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mensagem_ = value;
          onChanged();
        } else {
          mensagemTextoBuilder_.setMessage(value);
        }
        mensagemCase_ = 5;
        return this;
      }
      /**
       * <pre>
       * mensagem de texto
       * </pre>
       *
       * <code>.smgo.mensagem.MensagemTexto mensagemTexto = 5;</code>
       */
      public Builder setMensagemTexto(
          smgo.mensagem.Mensagem.MensagemTexto.Builder builderForValue) {
        if (mensagemTextoBuilder_ == null) {
          mensagem_ = builderForValue.build();
          onChanged();
        } else {
          mensagemTextoBuilder_.setMessage(builderForValue.build());
        }
        mensagemCase_ = 5;
        return this;
      }
      /**
       * <pre>
       * mensagem de texto
       * </pre>
       *
       * <code>.smgo.mensagem.MensagemTexto mensagemTexto = 5;</code>
       */
      public Builder mergeMensagemTexto(smgo.mensagem.Mensagem.MensagemTexto value) {
        if (mensagemTextoBuilder_ == null) {
          if (mensagemCase_ == 5 &&
              mensagem_ != smgo.mensagem.Mensagem.MensagemTexto.getDefaultInstance()) {
            mensagem_ = smgo.mensagem.Mensagem.MensagemTexto.newBuilder((smgo.mensagem.Mensagem.MensagemTexto) mensagem_)
                .mergeFrom(value).buildPartial();
          } else {
            mensagem_ = value;
          }
          onChanged();
        } else {
          if (mensagemCase_ == 5) {
            mensagemTextoBuilder_.mergeFrom(value);
          }
          mensagemTextoBuilder_.setMessage(value);
        }
        mensagemCase_ = 5;
        return this;
      }
      /**
       * <pre>
       * mensagem de texto
       * </pre>
       *
       * <code>.smgo.mensagem.MensagemTexto mensagemTexto = 5;</code>
       */
      public Builder clearMensagemTexto() {
        if (mensagemTextoBuilder_ == null) {
          if (mensagemCase_ == 5) {
            mensagemCase_ = 0;
            mensagem_ = null;
            onChanged();
          }
        } else {
          if (mensagemCase_ == 5) {
            mensagemCase_ = 0;
            mensagem_ = null;
          }
          mensagemTextoBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * mensagem de texto
       * </pre>
       *
       * <code>.smgo.mensagem.MensagemTexto mensagemTexto = 5;</code>
       */
      public smgo.mensagem.Mensagem.MensagemTexto.Builder getMensagemTextoBuilder() {
        return getMensagemTextoFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * mensagem de texto
       * </pre>
       *
       * <code>.smgo.mensagem.MensagemTexto mensagemTexto = 5;</code>
       */
      @java.lang.Override
      public smgo.mensagem.Mensagem.MensagemTextoOrBuilder getMensagemTextoOrBuilder() {
        if ((mensagemCase_ == 5) && (mensagemTextoBuilder_ != null)) {
          return mensagemTextoBuilder_.getMessageOrBuilder();
        } else {
          if (mensagemCase_ == 5) {
            return (smgo.mensagem.Mensagem.MensagemTexto) mensagem_;
          }
          return smgo.mensagem.Mensagem.MensagemTexto.getDefaultInstance();
        }
      }
      /**
       * <pre>
       * mensagem de texto
       * </pre>
       *
       * <code>.smgo.mensagem.MensagemTexto mensagemTexto = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          smgo.mensagem.Mensagem.MensagemTexto, smgo.mensagem.Mensagem.MensagemTexto.Builder, smgo.mensagem.Mensagem.MensagemTextoOrBuilder> 
          getMensagemTextoFieldBuilder() {
        if (mensagemTextoBuilder_ == null) {
          if (!(mensagemCase_ == 5)) {
            mensagem_ = smgo.mensagem.Mensagem.MensagemTexto.getDefaultInstance();
          }
          mensagemTextoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              smgo.mensagem.Mensagem.MensagemTexto, smgo.mensagem.Mensagem.MensagemTexto.Builder, smgo.mensagem.Mensagem.MensagemTextoOrBuilder>(
                  (smgo.mensagem.Mensagem.MensagemTexto) mensagem_,
                  getParentForChildren(),
                  isClean());
          mensagem_ = null;
        }
        mensagemCase_ = 5;
        onChanged();;
        return mensagemTextoBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          smgo.mensagem.Mensagem.MensagemAudio, smgo.mensagem.Mensagem.MensagemAudio.Builder, smgo.mensagem.Mensagem.MensagemAudioOrBuilder> mensagemAudioBuilder_;
      /**
       * <code>.smgo.mensagem.MensagemAudio mensagemAudio = 6;</code>
       * @return Whether the mensagemAudio field is set.
       */
      @java.lang.Override
      public boolean hasMensagemAudio() {
        return mensagemCase_ == 6;
      }
      /**
       * <code>.smgo.mensagem.MensagemAudio mensagemAudio = 6;</code>
       * @return The mensagemAudio.
       */
      @java.lang.Override
      public smgo.mensagem.Mensagem.MensagemAudio getMensagemAudio() {
        if (mensagemAudioBuilder_ == null) {
          if (mensagemCase_ == 6) {
            return (smgo.mensagem.Mensagem.MensagemAudio) mensagem_;
          }
          return smgo.mensagem.Mensagem.MensagemAudio.getDefaultInstance();
        } else {
          if (mensagemCase_ == 6) {
            return mensagemAudioBuilder_.getMessage();
          }
          return smgo.mensagem.Mensagem.MensagemAudio.getDefaultInstance();
        }
      }
      /**
       * <code>.smgo.mensagem.MensagemAudio mensagemAudio = 6;</code>
       */
      public Builder setMensagemAudio(smgo.mensagem.Mensagem.MensagemAudio value) {
        if (mensagemAudioBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mensagem_ = value;
          onChanged();
        } else {
          mensagemAudioBuilder_.setMessage(value);
        }
        mensagemCase_ = 6;
        return this;
      }
      /**
       * <code>.smgo.mensagem.MensagemAudio mensagemAudio = 6;</code>
       */
      public Builder setMensagemAudio(
          smgo.mensagem.Mensagem.MensagemAudio.Builder builderForValue) {
        if (mensagemAudioBuilder_ == null) {
          mensagem_ = builderForValue.build();
          onChanged();
        } else {
          mensagemAudioBuilder_.setMessage(builderForValue.build());
        }
        mensagemCase_ = 6;
        return this;
      }
      /**
       * <code>.smgo.mensagem.MensagemAudio mensagemAudio = 6;</code>
       */
      public Builder mergeMensagemAudio(smgo.mensagem.Mensagem.MensagemAudio value) {
        if (mensagemAudioBuilder_ == null) {
          if (mensagemCase_ == 6 &&
              mensagem_ != smgo.mensagem.Mensagem.MensagemAudio.getDefaultInstance()) {
            mensagem_ = smgo.mensagem.Mensagem.MensagemAudio.newBuilder((smgo.mensagem.Mensagem.MensagemAudio) mensagem_)
                .mergeFrom(value).buildPartial();
          } else {
            mensagem_ = value;
          }
          onChanged();
        } else {
          if (mensagemCase_ == 6) {
            mensagemAudioBuilder_.mergeFrom(value);
          }
          mensagemAudioBuilder_.setMessage(value);
        }
        mensagemCase_ = 6;
        return this;
      }
      /**
       * <code>.smgo.mensagem.MensagemAudio mensagemAudio = 6;</code>
       */
      public Builder clearMensagemAudio() {
        if (mensagemAudioBuilder_ == null) {
          if (mensagemCase_ == 6) {
            mensagemCase_ = 0;
            mensagem_ = null;
            onChanged();
          }
        } else {
          if (mensagemCase_ == 6) {
            mensagemCase_ = 0;
            mensagem_ = null;
          }
          mensagemAudioBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.smgo.mensagem.MensagemAudio mensagemAudio = 6;</code>
       */
      public smgo.mensagem.Mensagem.MensagemAudio.Builder getMensagemAudioBuilder() {
        return getMensagemAudioFieldBuilder().getBuilder();
      }
      /**
       * <code>.smgo.mensagem.MensagemAudio mensagemAudio = 6;</code>
       */
      @java.lang.Override
      public smgo.mensagem.Mensagem.MensagemAudioOrBuilder getMensagemAudioOrBuilder() {
        if ((mensagemCase_ == 6) && (mensagemAudioBuilder_ != null)) {
          return mensagemAudioBuilder_.getMessageOrBuilder();
        } else {
          if (mensagemCase_ == 6) {
            return (smgo.mensagem.Mensagem.MensagemAudio) mensagem_;
          }
          return smgo.mensagem.Mensagem.MensagemAudio.getDefaultInstance();
        }
      }
      /**
       * <code>.smgo.mensagem.MensagemAudio mensagemAudio = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          smgo.mensagem.Mensagem.MensagemAudio, smgo.mensagem.Mensagem.MensagemAudio.Builder, smgo.mensagem.Mensagem.MensagemAudioOrBuilder> 
          getMensagemAudioFieldBuilder() {
        if (mensagemAudioBuilder_ == null) {
          if (!(mensagemCase_ == 6)) {
            mensagem_ = smgo.mensagem.Mensagem.MensagemAudio.getDefaultInstance();
          }
          mensagemAudioBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              smgo.mensagem.Mensagem.MensagemAudio, smgo.mensagem.Mensagem.MensagemAudio.Builder, smgo.mensagem.Mensagem.MensagemAudioOrBuilder>(
                  (smgo.mensagem.Mensagem.MensagemAudio) mensagem_,
                  getParentForChildren(),
                  isClean());
          mensagem_ = null;
        }
        mensagemCase_ = 6;
        onChanged();;
        return mensagemAudioBuilder_;
      }

      private java.lang.Object comentariosAdicionais_ = "";
      /**
       * <pre>
       * comentario adicional
       * </pre>
       *
       * <code>string comentariosAdicionais = 4;</code>
       * @return The comentariosAdicionais.
       */
      public java.lang.String getComentariosAdicionais() {
        java.lang.Object ref = comentariosAdicionais_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          comentariosAdicionais_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * comentario adicional
       * </pre>
       *
       * <code>string comentariosAdicionais = 4;</code>
       * @return The bytes for comentariosAdicionais.
       */
      public com.google.protobuf.ByteString
          getComentariosAdicionaisBytes() {
        java.lang.Object ref = comentariosAdicionais_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          comentariosAdicionais_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * comentario adicional
       * </pre>
       *
       * <code>string comentariosAdicionais = 4;</code>
       * @param value The comentariosAdicionais to set.
       * @return This builder for chaining.
       */
      public Builder setComentariosAdicionais(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        comentariosAdicionais_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * comentario adicional
       * </pre>
       *
       * <code>string comentariosAdicionais = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearComentariosAdicionais() {
        
        comentariosAdicionais_ = getDefaultInstance().getComentariosAdicionais();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * comentario adicional
       * </pre>
       *
       * <code>string comentariosAdicionais = 4;</code>
       * @param value The bytes for comentariosAdicionais to set.
       * @return This builder for chaining.
       */
      public Builder setComentariosAdicionaisBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        comentariosAdicionais_ = value;
        onChanged();
        return this;
      }

      private smgo.posicao.PosicionamentoOuterClass.Posicionamento ultimaPosicao_;
      private com.google.protobuf.SingleFieldBuilderV3<
          smgo.posicao.PosicionamentoOuterClass.Posicionamento, smgo.posicao.PosicionamentoOuterClass.Posicionamento.Builder, smgo.posicao.PosicionamentoOuterClass.PosicionamentoOrBuilder> ultimaPosicaoBuilder_;
      /**
       * <pre>
       * Última posição do veículo quando a mensagem foi gerada
       * </pre>
       *
       * <code>.smgo.posicao.Posicionamento ultimaPosicao = 7;</code>
       * @return Whether the ultimaPosicao field is set.
       */
      public boolean hasUltimaPosicao() {
        return ultimaPosicaoBuilder_ != null || ultimaPosicao_ != null;
      }
      /**
       * <pre>
       * Última posição do veículo quando a mensagem foi gerada
       * </pre>
       *
       * <code>.smgo.posicao.Posicionamento ultimaPosicao = 7;</code>
       * @return The ultimaPosicao.
       */
      public smgo.posicao.PosicionamentoOuterClass.Posicionamento getUltimaPosicao() {
        if (ultimaPosicaoBuilder_ == null) {
          return ultimaPosicao_ == null ? smgo.posicao.PosicionamentoOuterClass.Posicionamento.getDefaultInstance() : ultimaPosicao_;
        } else {
          return ultimaPosicaoBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Última posição do veículo quando a mensagem foi gerada
       * </pre>
       *
       * <code>.smgo.posicao.Posicionamento ultimaPosicao = 7;</code>
       */
      public Builder setUltimaPosicao(smgo.posicao.PosicionamentoOuterClass.Posicionamento value) {
        if (ultimaPosicaoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ultimaPosicao_ = value;
          onChanged();
        } else {
          ultimaPosicaoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Última posição do veículo quando a mensagem foi gerada
       * </pre>
       *
       * <code>.smgo.posicao.Posicionamento ultimaPosicao = 7;</code>
       */
      public Builder setUltimaPosicao(
          smgo.posicao.PosicionamentoOuterClass.Posicionamento.Builder builderForValue) {
        if (ultimaPosicaoBuilder_ == null) {
          ultimaPosicao_ = builderForValue.build();
          onChanged();
        } else {
          ultimaPosicaoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Última posição do veículo quando a mensagem foi gerada
       * </pre>
       *
       * <code>.smgo.posicao.Posicionamento ultimaPosicao = 7;</code>
       */
      public Builder mergeUltimaPosicao(smgo.posicao.PosicionamentoOuterClass.Posicionamento value) {
        if (ultimaPosicaoBuilder_ == null) {
          if (ultimaPosicao_ != null) {
            ultimaPosicao_ =
              smgo.posicao.PosicionamentoOuterClass.Posicionamento.newBuilder(ultimaPosicao_).mergeFrom(value).buildPartial();
          } else {
            ultimaPosicao_ = value;
          }
          onChanged();
        } else {
          ultimaPosicaoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Última posição do veículo quando a mensagem foi gerada
       * </pre>
       *
       * <code>.smgo.posicao.Posicionamento ultimaPosicao = 7;</code>
       */
      public Builder clearUltimaPosicao() {
        if (ultimaPosicaoBuilder_ == null) {
          ultimaPosicao_ = null;
          onChanged();
        } else {
          ultimaPosicao_ = null;
          ultimaPosicaoBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Última posição do veículo quando a mensagem foi gerada
       * </pre>
       *
       * <code>.smgo.posicao.Posicionamento ultimaPosicao = 7;</code>
       */
      public smgo.posicao.PosicionamentoOuterClass.Posicionamento.Builder getUltimaPosicaoBuilder() {
        
        onChanged();
        return getUltimaPosicaoFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Última posição do veículo quando a mensagem foi gerada
       * </pre>
       *
       * <code>.smgo.posicao.Posicionamento ultimaPosicao = 7;</code>
       */
      public smgo.posicao.PosicionamentoOuterClass.PosicionamentoOrBuilder getUltimaPosicaoOrBuilder() {
        if (ultimaPosicaoBuilder_ != null) {
          return ultimaPosicaoBuilder_.getMessageOrBuilder();
        } else {
          return ultimaPosicao_ == null ?
              smgo.posicao.PosicionamentoOuterClass.Posicionamento.getDefaultInstance() : ultimaPosicao_;
        }
      }
      /**
       * <pre>
       * Última posição do veículo quando a mensagem foi gerada
       * </pre>
       *
       * <code>.smgo.posicao.Posicionamento ultimaPosicao = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          smgo.posicao.PosicionamentoOuterClass.Posicionamento, smgo.posicao.PosicionamentoOuterClass.Posicionamento.Builder, smgo.posicao.PosicionamentoOuterClass.PosicionamentoOrBuilder> 
          getUltimaPosicaoFieldBuilder() {
        if (ultimaPosicaoBuilder_ == null) {
          ultimaPosicaoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              smgo.posicao.PosicionamentoOuterClass.Posicionamento, smgo.posicao.PosicionamentoOuterClass.Posicionamento.Builder, smgo.posicao.PosicionamentoOuterClass.PosicionamentoOrBuilder>(
                  getUltimaPosicao(),
                  getParentForChildren(),
                  isClean());
          ultimaPosicao_ = null;
        }
        return ultimaPosicaoBuilder_;
      }

      private java.lang.Object chapaMotorista_ = "";
      /**
       * <pre>
       * Chapa do motorista que enviou a mensagem
       * </pre>
       *
       * <code>string chapaMotorista = 8;</code>
       * @return The chapaMotorista.
       */
      public java.lang.String getChapaMotorista() {
        java.lang.Object ref = chapaMotorista_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chapaMotorista_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Chapa do motorista que enviou a mensagem
       * </pre>
       *
       * <code>string chapaMotorista = 8;</code>
       * @return The bytes for chapaMotorista.
       */
      public com.google.protobuf.ByteString
          getChapaMotoristaBytes() {
        java.lang.Object ref = chapaMotorista_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chapaMotorista_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Chapa do motorista que enviou a mensagem
       * </pre>
       *
       * <code>string chapaMotorista = 8;</code>
       * @param value The chapaMotorista to set.
       * @return This builder for chaining.
       */
      public Builder setChapaMotorista(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chapaMotorista_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Chapa do motorista que enviou a mensagem
       * </pre>
       *
       * <code>string chapaMotorista = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearChapaMotorista() {
        
        chapaMotorista_ = getDefaultInstance().getChapaMotorista();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Chapa do motorista que enviou a mensagem
       * </pre>
       *
       * <code>string chapaMotorista = 8;</code>
       * @param value The bytes for chapaMotorista to set.
       * @return This builder for chaining.
       */
      public Builder setChapaMotoristaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        chapaMotorista_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smgo.mensagem.EnvioMensagem)
    }

    // @@protoc_insertion_point(class_scope:smgo.mensagem.EnvioMensagem)
    private static final smgo.mensagem.Mensagem.EnvioMensagem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smgo.mensagem.Mensagem.EnvioMensagem();
    }

    public static smgo.mensagem.Mensagem.EnvioMensagem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnvioMensagem>
        PARSER = new com.google.protobuf.AbstractParser<EnvioMensagem>() {
      @java.lang.Override
      public EnvioMensagem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnvioMensagem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EnvioMensagem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnvioMensagem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smgo.mensagem.Mensagem.EnvioMensagem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smgo_mensagem_MensagemTexto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smgo_mensagem_MensagemTexto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smgo_mensagem_MensagemAudio_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smgo_mensagem_MensagemAudio_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smgo_mensagem_EnvioMensagem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smgo_mensagem_EnvioMensagem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016mensagem.proto\022\rsmgo.mensagem\032\013comum.p" +
      "roto\032\024posicionamento.proto\"*\n\rMensagemTe" +
      "xto\022\n\n\002id\030\001 \001(\005\022\r\n\005texto\030\002 \001(\t\"\036\n\rMensag" +
      "emAudio\022\r\n\005audio\030\001 \001(\014\"\365\001\n\rEnvioMensagem" +
      "\0225\n\rmensagemTexto\030\005 \001(\0132\034.smgo.mensagem." +
      "MensagemTextoH\000\0225\n\rmensagemAudio\030\006 \001(\0132\034" +
      ".smgo.mensagem.MensagemAudioH\000\022\035\n\025coment" +
      "ariosAdicionais\030\004 \001(\t\0223\n\rultimaPosicao\030\007" +
      " \001(\0132\034.smgo.posicao.Posicionamento\022\026\n\016ch" +
      "apaMotorista\030\010 \001(\tB\n\n\010mensagemb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          smgo.Comum.getDescriptor(),
          smgo.posicao.PosicionamentoOuterClass.getDescriptor(),
        });
    internal_static_smgo_mensagem_MensagemTexto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smgo_mensagem_MensagemTexto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smgo_mensagem_MensagemTexto_descriptor,
        new java.lang.String[] { "Id", "Texto", });
    internal_static_smgo_mensagem_MensagemAudio_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smgo_mensagem_MensagemAudio_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smgo_mensagem_MensagemAudio_descriptor,
        new java.lang.String[] { "Audio", });
    internal_static_smgo_mensagem_EnvioMensagem_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smgo_mensagem_EnvioMensagem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smgo_mensagem_EnvioMensagem_descriptor,
        new java.lang.String[] { "MensagemTexto", "MensagemAudio", "ComentariosAdicionais", "UltimaPosicao", "ChapaMotorista", "Mensagem", });
    smgo.Comum.getDescriptor();
    smgo.posicao.PosicionamentoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
