// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comum.proto

package smgo;

public final class Comum {
  private Comum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code smgo.Sentido}
   */
  public enum Sentido
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NA = 0;</code>
     */
    NA(0),
    /**
     * <code>TP_TS = 1;</code>
     */
    TP_TS(1),
    /**
     * <code>TS_TP = 2;</code>
     */
    TS_TP(2),
    /**
     * <code>CIRCULAR = 3;</code>
     */
    CIRCULAR(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NA = 0;</code>
     */
    public static final int NA_VALUE = 0;
    /**
     * <code>TP_TS = 1;</code>
     */
    public static final int TP_TS_VALUE = 1;
    /**
     * <code>TS_TP = 2;</code>
     */
    public static final int TS_TP_VALUE = 2;
    /**
     * <code>CIRCULAR = 3;</code>
     */
    public static final int CIRCULAR_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Sentido valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Sentido forNumber(int value) {
      switch (value) {
        case 0: return NA;
        case 1: return TP_TS;
        case 2: return TS_TP;
        case 3: return CIRCULAR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Sentido>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Sentido> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Sentido>() {
            public Sentido findValueByNumber(int number) {
              return Sentido.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return smgo.Comum.getDescriptor().getEnumTypes().get(0);
    }

    private static final Sentido[] VALUES = values();

    public static Sentido valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Sentido(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:smgo.Sentido)
  }

  public interface PosicaoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smgo.Posicao)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code smgo.Posicao}
   */
  public static final class Posicao extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smgo.Posicao)
      PosicaoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Posicao.newBuilder() to construct.
    private Posicao(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Posicao() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Posicao();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Posicao(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              latitude_ = input.readDouble();
              break;
            }
            case 17: {

              longitude_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smgo.Comum.internal_static_smgo_Posicao_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smgo.Comum.internal_static_smgo_Posicao_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smgo.Comum.Posicao.class, smgo.Comum.Posicao.Builder.class);
    }

    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public double getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(latitude_) != 0) {
        output.writeDouble(1, latitude_);
      }
      if (java.lang.Double.doubleToRawLongBits(longitude_) != 0) {
        output.writeDouble(2, longitude_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(latitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (java.lang.Double.doubleToRawLongBits(longitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smgo.Comum.Posicao)) {
        return super.equals(obj);
      }
      smgo.Comum.Posicao other = (smgo.Comum.Posicao) obj;

      if (java.lang.Double.doubleToLongBits(getLatitude())
          != java.lang.Double.doubleToLongBits(
              other.getLatitude())) return false;
      if (java.lang.Double.doubleToLongBits(getLongitude())
          != java.lang.Double.doubleToLongBits(
              other.getLongitude())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLatitude()));
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLongitude()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smgo.Comum.Posicao parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.Comum.Posicao parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.Comum.Posicao parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.Comum.Posicao parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.Comum.Posicao parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.Comum.Posicao parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.Comum.Posicao parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.Comum.Posicao parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.Comum.Posicao parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smgo.Comum.Posicao parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.Comum.Posicao parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.Comum.Posicao parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smgo.Comum.Posicao prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code smgo.Posicao}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smgo.Posicao)
        smgo.Comum.PosicaoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smgo.Comum.internal_static_smgo_Posicao_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smgo.Comum.internal_static_smgo_Posicao_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smgo.Comum.Posicao.class, smgo.Comum.Posicao.Builder.class);
      }

      // Construct using smgo.Comum.Posicao.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        latitude_ = 0D;

        longitude_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smgo.Comum.internal_static_smgo_Posicao_descriptor;
      }

      @java.lang.Override
      public smgo.Comum.Posicao getDefaultInstanceForType() {
        return smgo.Comum.Posicao.getDefaultInstance();
      }

      @java.lang.Override
      public smgo.Comum.Posicao build() {
        smgo.Comum.Posicao result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smgo.Comum.Posicao buildPartial() {
        smgo.Comum.Posicao result = new smgo.Comum.Posicao(this);
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smgo.Comum.Posicao) {
          return mergeFrom((smgo.Comum.Posicao)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smgo.Comum.Posicao other) {
        if (other == smgo.Comum.Posicao.getDefaultInstance()) return this;
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smgo.Comum.Posicao parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smgo.Comum.Posicao) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double latitude_ ;
      /**
       * <code>double latitude = 1;</code>
       * @return The latitude.
       */
      @java.lang.Override
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>double latitude = 1;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double latitude = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>double longitude = 2;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>double longitude = 2;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double longitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        
        longitude_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smgo.Posicao)
    }

    // @@protoc_insertion_point(class_scope:smgo.Posicao)
    private static final smgo.Comum.Posicao DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smgo.Comum.Posicao();
    }

    public static smgo.Comum.Posicao getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Posicao>
        PARSER = new com.google.protobuf.AbstractParser<Posicao>() {
      @java.lang.Override
      public Posicao parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Posicao(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Posicao> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Posicao> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smgo.Comum.Posicao getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CabecalhoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smgo.Cabecalho)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * versao do protocolo descrito por este conjunto de arquivos .proto
     * </pre>
     *
     * <code>int32 versaoProtocolo = 1;</code>
     * @return The versaoProtocolo.
     */
    int getVersaoProtocolo();

    /**
     * <pre>
     * versao do firmware sendo executado na UCP
     * </pre>
     *
     * <code>int32 firmware = 2;</code>
     * @return The firmware.
     */
    int getFirmware();

    /**
     * <code>string identificadorEquipamento = 3;</code>
     * @return Whether the identificadorEquipamento field is set.
     */
    boolean hasIdentificadorEquipamento();
    /**
     * <code>string identificadorEquipamento = 3;</code>
     * @return The identificadorEquipamento.
     */
    java.lang.String getIdentificadorEquipamento();
    /**
     * <code>string identificadorEquipamento = 3;</code>
     * @return The bytes for identificadorEquipamento.
     */
    com.google.protobuf.ByteString
        getIdentificadorEquipamentoBytes();

    /**
     * <code>int64 numeroSerial = 4;</code>
     * @return Whether the numeroSerial field is set.
     */
    boolean hasNumeroSerial();
    /**
     * <code>int64 numeroSerial = 4;</code>
     * @return The numeroSerial.
     */
    long getNumeroSerial();

    /**
     * <pre>
     * data/hora do envio do pacote. Representado como numero de segundos desde o epoch ( 1 de janeiro de 1970 no fuso UTC [ GMT+0 ] )
     * </pre>
     *
     * <code>uint64 dataHora = 5;</code>
     * @return The dataHora.
     */
    long getDataHora();

    /**
     * <pre>
     * numero sequencial da mensagem, que pode ser usado como uma dica para deteccao de mensagens duplicadas
     * </pre>
     *
     * <code>int32 numeroSequencial = 6;</code>
     * @return The numeroSequencial.
     */
    int getNumeroSequencial();

    public smgo.Comum.Cabecalho.IdentificadorCase getIdentificadorCase();
  }
  /**
   * <pre>
   *todos os campos sao obrigatorios
   * </pre>
   *
   * Protobuf type {@code smgo.Cabecalho}
   */
  public static final class Cabecalho extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smgo.Cabecalho)
      CabecalhoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Cabecalho.newBuilder() to construct.
    private Cabecalho(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Cabecalho() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Cabecalho();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Cabecalho(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              versaoProtocolo_ = input.readInt32();
              break;
            }
            case 16: {

              firmware_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              identificadorCase_ = 3;
              identificador_ = s;
              break;
            }
            case 32: {
              identificador_ = input.readInt64();
              identificadorCase_ = 4;
              break;
            }
            case 40: {

              dataHora_ = input.readUInt64();
              break;
            }
            case 48: {

              numeroSequencial_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smgo.Comum.internal_static_smgo_Cabecalho_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smgo.Comum.internal_static_smgo_Cabecalho_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smgo.Comum.Cabecalho.class, smgo.Comum.Cabecalho.Builder.class);
    }

    private int identificadorCase_ = 0;
    private java.lang.Object identificador_;
    public enum IdentificadorCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      IDENTIFICADOREQUIPAMENTO(3),
      NUMEROSERIAL(4),
      IDENTIFICADOR_NOT_SET(0);
      private final int value;
      private IdentificadorCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static IdentificadorCase valueOf(int value) {
        return forNumber(value);
      }

      public static IdentificadorCase forNumber(int value) {
        switch (value) {
          case 3: return IDENTIFICADOREQUIPAMENTO;
          case 4: return NUMEROSERIAL;
          case 0: return IDENTIFICADOR_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public IdentificadorCase
    getIdentificadorCase() {
      return IdentificadorCase.forNumber(
          identificadorCase_);
    }

    public static final int VERSAOPROTOCOLO_FIELD_NUMBER = 1;
    private int versaoProtocolo_;
    /**
     * <pre>
     * versao do protocolo descrito por este conjunto de arquivos .proto
     * </pre>
     *
     * <code>int32 versaoProtocolo = 1;</code>
     * @return The versaoProtocolo.
     */
    @java.lang.Override
    public int getVersaoProtocolo() {
      return versaoProtocolo_;
    }

    public static final int FIRMWARE_FIELD_NUMBER = 2;
    private int firmware_;
    /**
     * <pre>
     * versao do firmware sendo executado na UCP
     * </pre>
     *
     * <code>int32 firmware = 2;</code>
     * @return The firmware.
     */
    @java.lang.Override
    public int getFirmware() {
      return firmware_;
    }

    public static final int IDENTIFICADOREQUIPAMENTO_FIELD_NUMBER = 3;
    /**
     * <code>string identificadorEquipamento = 3;</code>
     * @return Whether the identificadorEquipamento field is set.
     */
    public boolean hasIdentificadorEquipamento() {
      return identificadorCase_ == 3;
    }
    /**
     * <code>string identificadorEquipamento = 3;</code>
     * @return The identificadorEquipamento.
     */
    public java.lang.String getIdentificadorEquipamento() {
      java.lang.Object ref = "";
      if (identificadorCase_ == 3) {
        ref = identificador_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (identificadorCase_ == 3) {
          identificador_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string identificadorEquipamento = 3;</code>
     * @return The bytes for identificadorEquipamento.
     */
    public com.google.protobuf.ByteString
        getIdentificadorEquipamentoBytes() {
      java.lang.Object ref = "";
      if (identificadorCase_ == 3) {
        ref = identificador_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (identificadorCase_ == 3) {
          identificador_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMEROSERIAL_FIELD_NUMBER = 4;
    /**
     * <code>int64 numeroSerial = 4;</code>
     * @return Whether the numeroSerial field is set.
     */
    @java.lang.Override
    public boolean hasNumeroSerial() {
      return identificadorCase_ == 4;
    }
    /**
     * <code>int64 numeroSerial = 4;</code>
     * @return The numeroSerial.
     */
    @java.lang.Override
    public long getNumeroSerial() {
      if (identificadorCase_ == 4) {
        return (java.lang.Long) identificador_;
      }
      return 0L;
    }

    public static final int DATAHORA_FIELD_NUMBER = 5;
    private long dataHora_;
    /**
     * <pre>
     * data/hora do envio do pacote. Representado como numero de segundos desde o epoch ( 1 de janeiro de 1970 no fuso UTC [ GMT+0 ] )
     * </pre>
     *
     * <code>uint64 dataHora = 5;</code>
     * @return The dataHora.
     */
    @java.lang.Override
    public long getDataHora() {
      return dataHora_;
    }

    public static final int NUMEROSEQUENCIAL_FIELD_NUMBER = 6;
    private int numeroSequencial_;
    /**
     * <pre>
     * numero sequencial da mensagem, que pode ser usado como uma dica para deteccao de mensagens duplicadas
     * </pre>
     *
     * <code>int32 numeroSequencial = 6;</code>
     * @return The numeroSequencial.
     */
    @java.lang.Override
    public int getNumeroSequencial() {
      return numeroSequencial_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (versaoProtocolo_ != 0) {
        output.writeInt32(1, versaoProtocolo_);
      }
      if (firmware_ != 0) {
        output.writeInt32(2, firmware_);
      }
      if (identificadorCase_ == 3) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, identificador_);
      }
      if (identificadorCase_ == 4) {
        output.writeInt64(
            4, (long)((java.lang.Long) identificador_));
      }
      if (dataHora_ != 0L) {
        output.writeUInt64(5, dataHora_);
      }
      if (numeroSequencial_ != 0) {
        output.writeInt32(6, numeroSequencial_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (versaoProtocolo_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, versaoProtocolo_);
      }
      if (firmware_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, firmware_);
      }
      if (identificadorCase_ == 3) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, identificador_);
      }
      if (identificadorCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(
              4, (long)((java.lang.Long) identificador_));
      }
      if (dataHora_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, dataHora_);
      }
      if (numeroSequencial_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, numeroSequencial_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smgo.Comum.Cabecalho)) {
        return super.equals(obj);
      }
      smgo.Comum.Cabecalho other = (smgo.Comum.Cabecalho) obj;

      if (getVersaoProtocolo()
          != other.getVersaoProtocolo()) return false;
      if (getFirmware()
          != other.getFirmware()) return false;
      if (getDataHora()
          != other.getDataHora()) return false;
      if (getNumeroSequencial()
          != other.getNumeroSequencial()) return false;
      if (!getIdentificadorCase().equals(other.getIdentificadorCase())) return false;
      switch (identificadorCase_) {
        case 3:
          if (!getIdentificadorEquipamento()
              .equals(other.getIdentificadorEquipamento())) return false;
          break;
        case 4:
          if (getNumeroSerial()
              != other.getNumeroSerial()) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSAOPROTOCOLO_FIELD_NUMBER;
      hash = (53 * hash) + getVersaoProtocolo();
      hash = (37 * hash) + FIRMWARE_FIELD_NUMBER;
      hash = (53 * hash) + getFirmware();
      hash = (37 * hash) + DATAHORA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDataHora());
      hash = (37 * hash) + NUMEROSEQUENCIAL_FIELD_NUMBER;
      hash = (53 * hash) + getNumeroSequencial();
      switch (identificadorCase_) {
        case 3:
          hash = (37 * hash) + IDENTIFICADOREQUIPAMENTO_FIELD_NUMBER;
          hash = (53 * hash) + getIdentificadorEquipamento().hashCode();
          break;
        case 4:
          hash = (37 * hash) + NUMEROSERIAL_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getNumeroSerial());
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smgo.Comum.Cabecalho parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.Comum.Cabecalho parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.Comum.Cabecalho parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.Comum.Cabecalho parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.Comum.Cabecalho parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.Comum.Cabecalho parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.Comum.Cabecalho parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.Comum.Cabecalho parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.Comum.Cabecalho parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smgo.Comum.Cabecalho parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.Comum.Cabecalho parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.Comum.Cabecalho parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smgo.Comum.Cabecalho prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *todos os campos sao obrigatorios
     * </pre>
     *
     * Protobuf type {@code smgo.Cabecalho}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smgo.Cabecalho)
        smgo.Comum.CabecalhoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smgo.Comum.internal_static_smgo_Cabecalho_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smgo.Comum.internal_static_smgo_Cabecalho_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smgo.Comum.Cabecalho.class, smgo.Comum.Cabecalho.Builder.class);
      }

      // Construct using smgo.Comum.Cabecalho.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        versaoProtocolo_ = 0;

        firmware_ = 0;

        dataHora_ = 0L;

        numeroSequencial_ = 0;

        identificadorCase_ = 0;
        identificador_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smgo.Comum.internal_static_smgo_Cabecalho_descriptor;
      }

      @java.lang.Override
      public smgo.Comum.Cabecalho getDefaultInstanceForType() {
        return smgo.Comum.Cabecalho.getDefaultInstance();
      }

      @java.lang.Override
      public smgo.Comum.Cabecalho build() {
        smgo.Comum.Cabecalho result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smgo.Comum.Cabecalho buildPartial() {
        smgo.Comum.Cabecalho result = new smgo.Comum.Cabecalho(this);
        result.versaoProtocolo_ = versaoProtocolo_;
        result.firmware_ = firmware_;
        if (identificadorCase_ == 3) {
          result.identificador_ = identificador_;
        }
        if (identificadorCase_ == 4) {
          result.identificador_ = identificador_;
        }
        result.dataHora_ = dataHora_;
        result.numeroSequencial_ = numeroSequencial_;
        result.identificadorCase_ = identificadorCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smgo.Comum.Cabecalho) {
          return mergeFrom((smgo.Comum.Cabecalho)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smgo.Comum.Cabecalho other) {
        if (other == smgo.Comum.Cabecalho.getDefaultInstance()) return this;
        if (other.getVersaoProtocolo() != 0) {
          setVersaoProtocolo(other.getVersaoProtocolo());
        }
        if (other.getFirmware() != 0) {
          setFirmware(other.getFirmware());
        }
        if (other.getDataHora() != 0L) {
          setDataHora(other.getDataHora());
        }
        if (other.getNumeroSequencial() != 0) {
          setNumeroSequencial(other.getNumeroSequencial());
        }
        switch (other.getIdentificadorCase()) {
          case IDENTIFICADOREQUIPAMENTO: {
            identificadorCase_ = 3;
            identificador_ = other.identificador_;
            onChanged();
            break;
          }
          case NUMEROSERIAL: {
            setNumeroSerial(other.getNumeroSerial());
            break;
          }
          case IDENTIFICADOR_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smgo.Comum.Cabecalho parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smgo.Comum.Cabecalho) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int identificadorCase_ = 0;
      private java.lang.Object identificador_;
      public IdentificadorCase
          getIdentificadorCase() {
        return IdentificadorCase.forNumber(
            identificadorCase_);
      }

      public Builder clearIdentificador() {
        identificadorCase_ = 0;
        identificador_ = null;
        onChanged();
        return this;
      }


      private int versaoProtocolo_ ;
      /**
       * <pre>
       * versao do protocolo descrito por este conjunto de arquivos .proto
       * </pre>
       *
       * <code>int32 versaoProtocolo = 1;</code>
       * @return The versaoProtocolo.
       */
      @java.lang.Override
      public int getVersaoProtocolo() {
        return versaoProtocolo_;
      }
      /**
       * <pre>
       * versao do protocolo descrito por este conjunto de arquivos .proto
       * </pre>
       *
       * <code>int32 versaoProtocolo = 1;</code>
       * @param value The versaoProtocolo to set.
       * @return This builder for chaining.
       */
      public Builder setVersaoProtocolo(int value) {
        
        versaoProtocolo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * versao do protocolo descrito por este conjunto de arquivos .proto
       * </pre>
       *
       * <code>int32 versaoProtocolo = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersaoProtocolo() {
        
        versaoProtocolo_ = 0;
        onChanged();
        return this;
      }

      private int firmware_ ;
      /**
       * <pre>
       * versao do firmware sendo executado na UCP
       * </pre>
       *
       * <code>int32 firmware = 2;</code>
       * @return The firmware.
       */
      @java.lang.Override
      public int getFirmware() {
        return firmware_;
      }
      /**
       * <pre>
       * versao do firmware sendo executado na UCP
       * </pre>
       *
       * <code>int32 firmware = 2;</code>
       * @param value The firmware to set.
       * @return This builder for chaining.
       */
      public Builder setFirmware(int value) {
        
        firmware_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * versao do firmware sendo executado na UCP
       * </pre>
       *
       * <code>int32 firmware = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirmware() {
        
        firmware_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>string identificadorEquipamento = 3;</code>
       * @return Whether the identificadorEquipamento field is set.
       */
      @java.lang.Override
      public boolean hasIdentificadorEquipamento() {
        return identificadorCase_ == 3;
      }
      /**
       * <code>string identificadorEquipamento = 3;</code>
       * @return The identificadorEquipamento.
       */
      @java.lang.Override
      public java.lang.String getIdentificadorEquipamento() {
        java.lang.Object ref = "";
        if (identificadorCase_ == 3) {
          ref = identificador_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (identificadorCase_ == 3) {
            identificador_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string identificadorEquipamento = 3;</code>
       * @return The bytes for identificadorEquipamento.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getIdentificadorEquipamentoBytes() {
        java.lang.Object ref = "";
        if (identificadorCase_ == 3) {
          ref = identificador_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (identificadorCase_ == 3) {
            identificador_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string identificadorEquipamento = 3;</code>
       * @param value The identificadorEquipamento to set.
       * @return This builder for chaining.
       */
      public Builder setIdentificadorEquipamento(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  identificadorCase_ = 3;
        identificador_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string identificadorEquipamento = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentificadorEquipamento() {
        if (identificadorCase_ == 3) {
          identificadorCase_ = 0;
          identificador_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string identificadorEquipamento = 3;</code>
       * @param value The bytes for identificadorEquipamento to set.
       * @return This builder for chaining.
       */
      public Builder setIdentificadorEquipamentoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        identificadorCase_ = 3;
        identificador_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>int64 numeroSerial = 4;</code>
       * @return Whether the numeroSerial field is set.
       */
      public boolean hasNumeroSerial() {
        return identificadorCase_ == 4;
      }
      /**
       * <code>int64 numeroSerial = 4;</code>
       * @return The numeroSerial.
       */
      public long getNumeroSerial() {
        if (identificadorCase_ == 4) {
          return (java.lang.Long) identificador_;
        }
        return 0L;
      }
      /**
       * <code>int64 numeroSerial = 4;</code>
       * @param value The numeroSerial to set.
       * @return This builder for chaining.
       */
      public Builder setNumeroSerial(long value) {
        identificadorCase_ = 4;
        identificador_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 numeroSerial = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumeroSerial() {
        if (identificadorCase_ == 4) {
          identificadorCase_ = 0;
          identificador_ = null;
          onChanged();
        }
        return this;
      }

      private long dataHora_ ;
      /**
       * <pre>
       * data/hora do envio do pacote. Representado como numero de segundos desde o epoch ( 1 de janeiro de 1970 no fuso UTC [ GMT+0 ] )
       * </pre>
       *
       * <code>uint64 dataHora = 5;</code>
       * @return The dataHora.
       */
      @java.lang.Override
      public long getDataHora() {
        return dataHora_;
      }
      /**
       * <pre>
       * data/hora do envio do pacote. Representado como numero de segundos desde o epoch ( 1 de janeiro de 1970 no fuso UTC [ GMT+0 ] )
       * </pre>
       *
       * <code>uint64 dataHora = 5;</code>
       * @param value The dataHora to set.
       * @return This builder for chaining.
       */
      public Builder setDataHora(long value) {
        
        dataHora_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * data/hora do envio do pacote. Representado como numero de segundos desde o epoch ( 1 de janeiro de 1970 no fuso UTC [ GMT+0 ] )
       * </pre>
       *
       * <code>uint64 dataHora = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataHora() {
        
        dataHora_ = 0L;
        onChanged();
        return this;
      }

      private int numeroSequencial_ ;
      /**
       * <pre>
       * numero sequencial da mensagem, que pode ser usado como uma dica para deteccao de mensagens duplicadas
       * </pre>
       *
       * <code>int32 numeroSequencial = 6;</code>
       * @return The numeroSequencial.
       */
      @java.lang.Override
      public int getNumeroSequencial() {
        return numeroSequencial_;
      }
      /**
       * <pre>
       * numero sequencial da mensagem, que pode ser usado como uma dica para deteccao de mensagens duplicadas
       * </pre>
       *
       * <code>int32 numeroSequencial = 6;</code>
       * @param value The numeroSequencial to set.
       * @return This builder for chaining.
       */
      public Builder setNumeroSequencial(int value) {
        
        numeroSequencial_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * numero sequencial da mensagem, que pode ser usado como uma dica para deteccao de mensagens duplicadas
       * </pre>
       *
       * <code>int32 numeroSequencial = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumeroSequencial() {
        
        numeroSequencial_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smgo.Cabecalho)
    }

    // @@protoc_insertion_point(class_scope:smgo.Cabecalho)
    private static final smgo.Comum.Cabecalho DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smgo.Comum.Cabecalho();
    }

    public static smgo.Comum.Cabecalho getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Cabecalho>
        PARSER = new com.google.protobuf.AbstractParser<Cabecalho>() {
      @java.lang.Override
      public Cabecalho parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cabecalho(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Cabecalho> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Cabecalho> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smgo.Comum.Cabecalho getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MensagemErroOrBuilder extends
      // @@protoc_insertion_point(interface_extends:smgo.MensagemErro)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * comando que gerou o erro
     * </pre>
     *
     * <code>uint32 numeroSequencialComando = 1;</code>
     * @return The numeroSequencialComando.
     */
    int getNumeroSequencialComando();

    /**
     * <pre>
     * detalhes do erro, se houver
     * </pre>
     *
     * <code>string detalhes = 2;</code>
     * @return The detalhes.
     */
    java.lang.String getDetalhes();
    /**
     * <pre>
     * detalhes do erro, se houver
     * </pre>
     *
     * <code>string detalhes = 2;</code>
     * @return The bytes for detalhes.
     */
    com.google.protobuf.ByteString
        getDetalhesBytes();
  }
  /**
   * <pre>
   * enviado em resposta a um comando, para indicar que houve um erro na interpretacao do comando
   * </pre>
   *
   * Protobuf type {@code smgo.MensagemErro}
   */
  public static final class MensagemErro extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:smgo.MensagemErro)
      MensagemErroOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MensagemErro.newBuilder() to construct.
    private MensagemErro(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MensagemErro() {
      detalhes_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MensagemErro();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MensagemErro(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              numeroSequencialComando_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              detalhes_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smgo.Comum.internal_static_smgo_MensagemErro_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smgo.Comum.internal_static_smgo_MensagemErro_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              smgo.Comum.MensagemErro.class, smgo.Comum.MensagemErro.Builder.class);
    }

    public static final int NUMEROSEQUENCIALCOMANDO_FIELD_NUMBER = 1;
    private int numeroSequencialComando_;
    /**
     * <pre>
     * comando que gerou o erro
     * </pre>
     *
     * <code>uint32 numeroSequencialComando = 1;</code>
     * @return The numeroSequencialComando.
     */
    @java.lang.Override
    public int getNumeroSequencialComando() {
      return numeroSequencialComando_;
    }

    public static final int DETALHES_FIELD_NUMBER = 2;
    private volatile java.lang.Object detalhes_;
    /**
     * <pre>
     * detalhes do erro, se houver
     * </pre>
     *
     * <code>string detalhes = 2;</code>
     * @return The detalhes.
     */
    @java.lang.Override
    public java.lang.String getDetalhes() {
      java.lang.Object ref = detalhes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        detalhes_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * detalhes do erro, se houver
     * </pre>
     *
     * <code>string detalhes = 2;</code>
     * @return The bytes for detalhes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDetalhesBytes() {
      java.lang.Object ref = detalhes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        detalhes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (numeroSequencialComando_ != 0) {
        output.writeUInt32(1, numeroSequencialComando_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(detalhes_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, detalhes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (numeroSequencialComando_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, numeroSequencialComando_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(detalhes_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, detalhes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof smgo.Comum.MensagemErro)) {
        return super.equals(obj);
      }
      smgo.Comum.MensagemErro other = (smgo.Comum.MensagemErro) obj;

      if (getNumeroSequencialComando()
          != other.getNumeroSequencialComando()) return false;
      if (!getDetalhes()
          .equals(other.getDetalhes())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMEROSEQUENCIALCOMANDO_FIELD_NUMBER;
      hash = (53 * hash) + getNumeroSequencialComando();
      hash = (37 * hash) + DETALHES_FIELD_NUMBER;
      hash = (53 * hash) + getDetalhes().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static smgo.Comum.MensagemErro parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.Comum.MensagemErro parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.Comum.MensagemErro parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.Comum.MensagemErro parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.Comum.MensagemErro parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static smgo.Comum.MensagemErro parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static smgo.Comum.MensagemErro parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.Comum.MensagemErro parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.Comum.MensagemErro parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static smgo.Comum.MensagemErro parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static smgo.Comum.MensagemErro parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static smgo.Comum.MensagemErro parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(smgo.Comum.MensagemErro prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * enviado em resposta a um comando, para indicar que houve um erro na interpretacao do comando
     * </pre>
     *
     * Protobuf type {@code smgo.MensagemErro}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:smgo.MensagemErro)
        smgo.Comum.MensagemErroOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return smgo.Comum.internal_static_smgo_MensagemErro_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return smgo.Comum.internal_static_smgo_MensagemErro_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                smgo.Comum.MensagemErro.class, smgo.Comum.MensagemErro.Builder.class);
      }

      // Construct using smgo.Comum.MensagemErro.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        numeroSequencialComando_ = 0;

        detalhes_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smgo.Comum.internal_static_smgo_MensagemErro_descriptor;
      }

      @java.lang.Override
      public smgo.Comum.MensagemErro getDefaultInstanceForType() {
        return smgo.Comum.MensagemErro.getDefaultInstance();
      }

      @java.lang.Override
      public smgo.Comum.MensagemErro build() {
        smgo.Comum.MensagemErro result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public smgo.Comum.MensagemErro buildPartial() {
        smgo.Comum.MensagemErro result = new smgo.Comum.MensagemErro(this);
        result.numeroSequencialComando_ = numeroSequencialComando_;
        result.detalhes_ = detalhes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smgo.Comum.MensagemErro) {
          return mergeFrom((smgo.Comum.MensagemErro)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(smgo.Comum.MensagemErro other) {
        if (other == smgo.Comum.MensagemErro.getDefaultInstance()) return this;
        if (other.getNumeroSequencialComando() != 0) {
          setNumeroSequencialComando(other.getNumeroSequencialComando());
        }
        if (!other.getDetalhes().isEmpty()) {
          detalhes_ = other.detalhes_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        smgo.Comum.MensagemErro parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (smgo.Comum.MensagemErro) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int numeroSequencialComando_ ;
      /**
       * <pre>
       * comando que gerou o erro
       * </pre>
       *
       * <code>uint32 numeroSequencialComando = 1;</code>
       * @return The numeroSequencialComando.
       */
      @java.lang.Override
      public int getNumeroSequencialComando() {
        return numeroSequencialComando_;
      }
      /**
       * <pre>
       * comando que gerou o erro
       * </pre>
       *
       * <code>uint32 numeroSequencialComando = 1;</code>
       * @param value The numeroSequencialComando to set.
       * @return This builder for chaining.
       */
      public Builder setNumeroSequencialComando(int value) {
        
        numeroSequencialComando_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * comando que gerou o erro
       * </pre>
       *
       * <code>uint32 numeroSequencialComando = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumeroSequencialComando() {
        
        numeroSequencialComando_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object detalhes_ = "";
      /**
       * <pre>
       * detalhes do erro, se houver
       * </pre>
       *
       * <code>string detalhes = 2;</code>
       * @return The detalhes.
       */
      public java.lang.String getDetalhes() {
        java.lang.Object ref = detalhes_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          detalhes_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * detalhes do erro, se houver
       * </pre>
       *
       * <code>string detalhes = 2;</code>
       * @return The bytes for detalhes.
       */
      public com.google.protobuf.ByteString
          getDetalhesBytes() {
        java.lang.Object ref = detalhes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          detalhes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * detalhes do erro, se houver
       * </pre>
       *
       * <code>string detalhes = 2;</code>
       * @param value The detalhes to set.
       * @return This builder for chaining.
       */
      public Builder setDetalhes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        detalhes_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * detalhes do erro, se houver
       * </pre>
       *
       * <code>string detalhes = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDetalhes() {
        
        detalhes_ = getDefaultInstance().getDetalhes();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * detalhes do erro, se houver
       * </pre>
       *
       * <code>string detalhes = 2;</code>
       * @param value The bytes for detalhes to set.
       * @return This builder for chaining.
       */
      public Builder setDetalhesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        detalhes_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:smgo.MensagemErro)
    }

    // @@protoc_insertion_point(class_scope:smgo.MensagemErro)
    private static final smgo.Comum.MensagemErro DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new smgo.Comum.MensagemErro();
    }

    public static smgo.Comum.MensagemErro getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MensagemErro>
        PARSER = new com.google.protobuf.AbstractParser<MensagemErro>() {
      @java.lang.Override
      public MensagemErro parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MensagemErro(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MensagemErro> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MensagemErro> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public smgo.Comum.MensagemErro getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smgo_Posicao_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smgo_Posicao_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smgo_Cabecalho_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smgo_Cabecalho_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_smgo_MensagemErro_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_smgo_MensagemErro_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013comum.proto\022\004smgo\".\n\007Posicao\022\020\n\010latitu" +
      "de\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001\"\257\001\n\tCabecalh" +
      "o\022\027\n\017versaoProtocolo\030\001 \001(\005\022\020\n\010firmware\030\002" +
      " \001(\005\022\"\n\030identificadorEquipamento\030\003 \001(\tH\000" +
      "\022\026\n\014numeroSerial\030\004 \001(\003H\000\022\020\n\010dataHora\030\005 \001" +
      "(\004\022\030\n\020numeroSequencial\030\006 \001(\005B\017\n\ridentifi" +
      "cador\"A\n\014MensagemErro\022\037\n\027numeroSequencia" +
      "lComando\030\001 \001(\r\022\020\n\010detalhes\030\002 \001(\t*5\n\007Sent" +
      "ido\022\006\n\002NA\020\000\022\t\n\005TP_TS\020\001\022\t\n\005TS_TP\020\002\022\014\n\010CIR" +
      "CULAR\020\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_smgo_Posicao_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_smgo_Posicao_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smgo_Posicao_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_smgo_Cabecalho_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_smgo_Cabecalho_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smgo_Cabecalho_descriptor,
        new java.lang.String[] { "VersaoProtocolo", "Firmware", "IdentificadorEquipamento", "NumeroSerial", "DataHora", "NumeroSequencial", "Identificador", });
    internal_static_smgo_MensagemErro_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_smgo_MensagemErro_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_smgo_MensagemErro_descriptor,
        new java.lang.String[] { "NumeroSequencialComando", "Detalhes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
